DbBundle\Entity\AuditRevisionLog:
    type: entity
    table: audit_revision_log
    id:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
            column: audit_revision_log_id
            options:
                unsigned: true
    indexes:
        operation_index:
            columns: [audit_revision_log_operation]
        category_index:
            columns: [audit_revision_log_category]
        identifier_index:
            columns: [audit_revision_log_identifier]
        className_index:
            columns: [audit_revision_log_class_name]
        label_index:
            columns: [audit_revision_log_label]
    fields:
        details:
            type: json
            column: audit_revision_log_details
        operation:
            type: smallint
            column: audit_revision_log_operation
        category:
            type: smallint
            column: audit_revision_log_category
        className:
            type: string
            options:
                generate: JSON_UNQUOTE(JSON_EXTRACT(audit_revision_log_details,'$.class_name'))
                readOnly: true
            column: audit_revision_log_class_name
            nullable: true
        identifier:
            type: string
            options:
                generate: JSON_UNQUOTE(JSON_EXTRACT(audit_revision_log_details,'$.identifier'))
                readOnly: true
            column: audit_revision_log_identifier
            nullable: true
        label:
            type: string
            options:
                generate: JSON_UNQUOTE(JSON_EXTRACT(audit_revision_log_details,'$.label'))
                readOnly: true
            column: audit_revision_log_label
            nullable: true
    manyToOne:
        auditRevision:
            targetEntity: DbBundle\Entity\AuditRevision
            joinColumn:
                name: audit_revision_log_audit_revision_id
                referencedColumnName: audit_revision_id