DbBundle\Entity\Customer:
    type: entity
    table: customer
    repositoryClass: DbBundle\Repository\CustomerRepository
    id:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
            column: customer_id
            options:
                unsigned: true
    indexes:
        fname_index:
            columns: [customer_fname]
        lname_index:
            columns: [customer_lname]
        fullname_index:
            columns: [customer_full_name]
    fields:
        fName:
            type: string
            length: 64
            column: customer_fname
            nullable: true
            options:
                default: ''
        mName:
            type: string
            length: 64
            column: customer_mname
            nullable: true
            options:
                default: ''
        lName:
            type: string
            length: 64
            column: customer_lname
            nullable: true
            options:
                default: ''
        fullName:
            type: string
            length: 150
            column: customer_full_name
        isCustomer:
            type: boolean
            column: customer_is_customer
            options:
                default: true
        isAffiliate:
            type: boolean
            column: customer_is_affiliate
            options:
                default: false
        birthDate:
            type: date
            column: customer_birthdate
            nullable: true
        balance:
            type: decimal
            column: customer_balance
            precision: 65
            scale: 10
            options:
                default: 0
        socials:
            type: json
            column: customer_socials
        transactionPassword:
            type: string
            column: customer_transaction_password
        level:
            type: integer
            options:
                default: 1
            column: customer_level
        verifiedAt:
            type: datetime
            nullable: true
            column: customer_verified_at
        details:
            type: json
            column: customer_other_details
        joinedAt:
            type: datetime
            column: customer_joined_at
        files:
            type: json
            column: customer_files
        contacts:
            type: json
            column: customer_contacts
        notifications:
            type: json
            column: customer_notifications
            nullable: true
        # This would be string not association
        # because the RiskSetting entity is versionable.
        riskSetting:
            type: string
            column: customer_risk_setting
            nullable: true
        tags:
            type: json
            column: customer_tags
            nullable: false
            options:
                default: ''
        phoneNumber:
            type: string
            column: customer_phone_number
        pinUserCode:
            type: string
            column: customer_pin_user_code
        pinLoginId:
            type: string
            column: customer_pin_login_id
    manyToOne:
        currency:
            targetEntity: DbBundle\Entity\Currency
            joinColumn:
                nullable: true
                name: customer_currency_id
                referencedColumnName: currency_id
        country:
            targetEntity: DbBundle\Entity\Country
            nullable: true
            joinColumn:
                nullable: true
                name: customer_country_id
                referencedColumnName: country_id

        affiliate:
            targetEntity: DbBundle\Entity\Customer
            joinColumn:
                name: customer_affiliate_id
                referencedColumnName: customer_id
    oneToOne:
        user:
            targetEntity: DbBundle\Entity\User
            inversedBy: customer
            joinColumn:
                nullable: false
                unique: true
                name: customer_user_id
                referencedColumnName: user_id
            cascade: ['persist']
    manyToMany:
        groups:
            targetEntity: DbBundle\Entity\CustomerGroup
            inversedBy: customers
            joinTable:
                name: customer_groups
                joinColumns:
                    ccg_customer_id:
                        referencedColumnName: customer_id
                inverseJoinColumns:
                    ccg_customer_group_id:
                        referencedColumnName: customer_group_id
            cascade: ['persist']
    oneToMany:
        transactions:
            targetEntity: DbBundle\Entity\Transaction
            mappedBy: customer
            cascade: [ persist ]
        paymentOptions:
            targetEntity: DbBundle\Entity\CustomerPaymentOption
            mappedBy: customer
            cascade: [ persist ]
        products:
            targetEntity: DbBundle\Entity\CustomerProduct
            mappedBy: customer
            cascade: [ persist ]
        referrals:
            targetEntity: DbBundle\Entity\Customer
            mappedBy: affiliate
            cascade: [ persist ]