DbBundle\Entity\MemberRunningCommission:
    type: entity
    table: member_running_commission
    repositoryClass: DbBundle\Repository\MemberRunningCommissionRepository
    id:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
            column: member_running_commission_id
            options:
                unsigned: true
    fields:
        runningCommission:
            type: decimal
            precision: 65
            scale: 10
            options:
                default: 0
            column: member_running_commission_total
            nullable: false
        commission:
            type: decimal
            precision: 65
            scale: 10
            options:
                default: 0
            column: member_running_commission_commission
            nullable: false
        status:
            type: string
            column: member_running_commission_status
            nullable: false
        processStatus:
            type: tinyint
            column: member_running_commission_process_status
            nullable: false
            options:
                default: 1
        metaData:
            type: metadata
            column: member_running_commission_metadata
            nullable: false
        updatedBy:
            type: bigint
            nullable: true
            column: member_running_commission_updated_by
            options:
                unsigned: true
        updatedAt:
            type: datetime
            column: member_running_commission_updated_at
            nullable: true
        createdBy:
            type: bigint
            column: member_running_commission_created_by
            options:
                unsigned: true
            nullable: false
        createdAt:
            type: datetime
            column: member_running_commission_created_at
            nullable: false
    manyToOne:
        memberProduct:
            targetEntity: DbBundle\Entity\CustomerProduct
            joinColumn:
                name: member_running_commission_cproduct_id
                referencedColumnName: cproduct_id
        commissionPeriod:
            targetEntity: DbBundle\Entity\CommissionPeriod
            joinColumn:
                name: member_running_commission_period_id
                referencedColumnName: commission_period_id
    oneToOne:
        commissionTransaction:
            targetEntity: DbBundle\Entity\Transaction
            joinColumn:
                name: member_running_commission_transaction_id
                referencedColumnName: transaction_id
        preceedingRunningCommission:
            targetEntity: DbBundle\Entity\MemberRunningCommission
            joinColumn:
                name: member_running_commission_preceeding_id
                referencedColumnName: member_running_commission_id
        succeedingRunningCommission:
            targetEntity: DbBundle\Entity\MemberRunningCommission
            joinColumn:
                name: member_running_commission_succeeding_id
                referencedColumnName: member_running_commission_id
