DbBundle\Entity\MemberRunningRevenueShare:
    type: entity
    table: member_running_revenue_share
    repositoryClass: DbBundle\Repository\MemberRunningRevenueShareRepository
    id:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
            column: member_running_revenue_share_id
            options:
                unsigned: true
    fields:
        runningRevenueShare:
            type: decimal
            precision: 65
            scale: 10
            options:
                default: 0
            column: member_running_revenue_share_total
            nullable: false
        revenueShare:
            type: decimal
            precision: 65
            scale: 10
            options:
                default: 0
            column: member_running_revenue_share_revenue_share
            nullable: false
        status:
            type: string
            column: member_running_revenue_share_status
            nullable: false
        processStatus:
            type: tinyint
            column: member_running_revenue_share_process_status
            nullable: false
            options:
                default: 1
        metaData:
            type: metadata
            column: member_running_revenue_share_metadata
            nullable: false
        updatedBy:
            type: bigint
            nullable: true
            column: member_running_revenue_share_updated_by
            options:
                unsigned: true
        updatedAt:
            type: datetime
            column: member_running_revenue_share_updated_at
            nullable: true
        createdBy:
            type: bigint
            column: member_running_revenue_share_created_by
            options:
                unsigned: true
            nullable: false
        createdAt:
            type: datetime
            column: member_running_revenue_share_created_at
            nullable: false
    manyToOne:
        member:
            targetEntity: DbBundle\Entity\Customer
            joinColumn:
                name: member_running_revenue_share_member_id
                referencedColumnName: customer_id
        revenueSharePeriod:
            targetEntity: DbBundle\Entity\CommissionPeriod
            joinColumn:
                name: member_running_revenue_share_period_id
                referencedColumnName: commission_period_id
    oneToOne:
        revenueShareTransaction:
            targetEntity: DbBundle\Entity\Transaction
            joinColumn:
                name: member_running_revenue_share_transaction_id
                referencedColumnName: transaction_id
        precedingRunningRevenueShare:
            targetEntity: DbBundle\Entity\MemberRunningRevenueShare
            joinColumn:
                name: member_running_revenue_share_preceding_id
                referencedColumnName: member_running_revenue_share_id
        succeedingRunningRevenueShare:
            targetEntity: DbBundle\Entity\MemberRunningRevenueShare
            joinColumn:
                name: member_running_revenue_share_succeeding_id
                referencedColumnName: member_running_revenue_share_id
