DbBundle\Entity\MemberRevenueShare:
  type: entity
  table: member_revenue_share
  repositoryClass: DbBundle\Repository\MemberRevenueShareRepository
  id:
    id:
      type: bigint
      id: true
      generator:
        strategy: AUTO
      column: member_revenue_share_id
      options:
        unsigned: true
  indexes:
    status_index:
      columns: [member_revenue_share_status]
    resource_index:
      columns: [member_revenue_share_resource_id]
    product_index:
      columns: [member_revenue_share_product_id]
    version_index:
      columns: [member_revenue_share_version]
    member_index:
      columns: [member_revenue_share_member_id]
    isLatest_index:
      columns: [member_revenue_share_is_latest]
  uniqueConstraints:
    resource_version_unq:
      columns: [member_revenue_share_resource_id, member_revenue_share_version]
  fields:
    resourceId:
      type: string
      nullable: false
      column: member_revenue_share_resource_id
    settings:
      type: json
      column: member_revenue_share_settings
    version:
      type: integer
      nullable: false
      column: member_revenue_share_version
      options:
        unsigned: true
        default: 1
    status:
      type: smallint
      column: member_revenue_share_status
      options:
        default: 1
        unsigned: true
      nullable: false
    isLatest:
      type: boolean
      column: member_revenue_share_is_latest
      nullable: false
      options:
        default: 1
        unsigned: true
    createdBy:
      type: bigint
      column: member_revenue_share_created_by
      options:
        unsigned: true
    createdAt:
      type: datetime
      column: member_revenue_share_created_at
      nullable: false
  manyToOne:
    member:
      targetEntity: DbBundle\Entity\Customer
      joinColumn:
        nullable: false
        name: member_revenue_share_member_id
        referencedColumnName: customer_id
    product:
      targetEntity: DbBundle\Entity\Product
      joinColumn:
        nullable: false
        name: member_revenue_share_product_id
        referencedColumnName: product_id
