DbBundle\Entity\MemberReferralName:
    type: entity
    table: member_referral_name
    repositoryClass: DbBundle\Repository\MemberReferralNameRepository
    id:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
            column: member_referral_name_id
            options:
                unsigned: true
    indexes:
        name_index:
            columns: [member_referral_name_name]
        member_index:
            columns: [member_referral_name_member_id]
    uniqueConstraints:
        name_unq:
            columns: [member_referral_name_name]
    fields:
        name:
            type: string
            length: 100
            column: member_referral_name_name
        isActive:
            type: boolean
            length: 1
            column: member_referral_name_is_active
            options:
                default: 1
        updatedBy:
            type: bigint
            nullable: true
            column: member_referral_name_updated_by
            options:
                unsigned: true
        updatedAt:
            type: datetime
            column: member_referral_name_updated_at
            nullable: true
        createdBy:
            type: bigint
            column: member_referral_name_created_by
            options:
                unsigned: true
        createdAt:
            type: datetime
            column: member_referral_name_created_at
    manyToOne:
        member:
            targetEntity: DbBundle\Entity\Customer
            joinColumn:
                name: member_referral_name_member_id
                referencedColumnName: customer_id