DbBundle\Entity\OAuth2\AuthCode:
    type: entity
    table: oauth2_auth_code
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToOne:
        client:
            targetEntity: DbBundle\Entity\OAuth2\Client
            joinColumn:
                name: client_id
                referencedColumnName: id
        user:
            targetEntity: DbBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: user_id