version: "3.7"
x-environment: &php-env
    environment:
      - SYMFONY_ENV=dev
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=ThisTokenIsNotSoSecretChangeIt
      - CUSTOMER_TEMP_PASSWORD=super@c66p@$$w0rd
      - JWT_KEY=YourSampleKeyHere
      - SLACK_TOKEN=xoxp-190886717379-465628275376-480332621415-5498caaeea6af3c795381717e3194787
      - SLACK_CHANNEL=cyd-piwi-error
      - MAIL_TRANSPORT=smtp
      - MAIL_HOST=mailhog
      - MAIL_USER=~
      - MAIL_PORT=25
      - MAIL_PASSWORD=~
      - MAIL_FROM=support@piwi247.com
      - MAIL_ENCRYPTION=~
      - PIN_API_URL=http://pinnacle.pinny88.com/b2b
      - PIN_API_AGENT_KEY=035c48be-9959-4556-80eb-9a0224814c88
      - PIN_API_SECRET_KEY=P6Aae0ej2dwnJe9B
      - PIN_AGENT_CODE=PS711
      - EVOLUTION_SERVICE_URL=http://evolution-service
      - PINNACLE_SERVICE_URL=http://api-gateway/api/v1/pinnacle
      - TWILIO_SID=ACa8414b7fd5f78fa371c0aeb341931c8d
      - TWILIO_TOKEN=e4815df706ef97c0017a7a1f2e37b928
      - TWILIO_FROM=972525436769
      - WS_URL=ws://localhost:8082/ws/
      - WS_WAMP_URL=http://websocket
      - DATABASE_DRIVER=pdo_mysql
      - DATABASE_HOST=database
      - DATABASE_NAME=backoffice_db
      - DATABASE_USER=backoffice
      - DATABASE_PASSWORD=backoffice_pass
      - DATABASE_PORT=3306
      - DATABASE_REPLICA_HOST=database
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
      - REDIS_REPLICA_HOST=redis
      - REDIS_REPLICA_PORT=6379
      - ECOPAYZ_TEST_MODE=true
      - BC_KEY=2db87356-bfbb-412d-8403-39b669cd9a9d
      - BC_WALLET_URL=http://wallet:3000
      - BC_XPUB__HOST=wallet
      - BC_XPUB_PORT=22
      - BC_XPUB__USER=xpub
      - BC_XPUB__PASSWORD=zmtsysxpub
      - BC_CALLBACK_HOST=https://cydrick.serveo.net
      - TRUSTED_PROXIES=172.0.0.0/8,10.0.0.0/8,192.0.0.0/8
      - TIMEZONE=Etc/GMT+4
      - MSERVICE_USERNAME=admin
      - MSERVICE_PASSWORD=admin
      - AWS_SDK_VERSION=latest
      - AWS_REGION=ap-northeast-1
      - AWS_KEY=AKIAQL3DDVH5O4PHGNEV
      - AWS_SECRET=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
      - AWS_S3_VERSION=2006-03-01
      - AWS_BUCKET=zmt-piwi
      - CUSTOMER_FOLDER=customerDocuments
      - UPLOAD_FOLDER=/uploads
      - SESSION_EXPIRATION_TIME=3600
      - ACCESS_TOKEN_EXPIRES_IN=3600
      - API_GATEWAY_URL=http://api-gateway/api/v1
      - API_GATEWAY_SERVICE=http://api-gateway
      - EWL_URL=http://api-gateway/api/v1/ewl
services:
  database:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql
    environment:
      - TZ=America/Manaus
      - MYSQL_ROOT_PASSWORD=backoffice_pass
      - MYSQL_PASSWORD=backoffice_pass
      - MYSQL_DATABASE=backoffice_db
      - MYSQL_USER=backoffice
      - SESSION_EXPIRATION_TIME=86400
      - API_GATEWAY_SERVICE=http://api-gateway
      - EWL_URL=http://api-gateway/api/v1/ewl
    networks:
      - piwinet

  mailhog:
    image: koalaphils/mailhog
    command:
      - "-smtp-bind-addr"
      - "0.0.0.0:25"
    user: root
    ports:
      - 8025:8025 
    networks:
      - piwinet

  adminer:
    image: adminer
    ports:
      - 9080:8080
    networks:
      - piwinet

  piwibo-php:
    <<: *php-env
    build:
      context: .
      target: prod
    image: php-container
    volumes:
      - .:/var/www/html
      # - .:/var/www/html:cached
      # - bo_cache:/var/www/html/var/cache
      # - uploads:/uploads:cached
    depends_on:
      - database
      - mailhog
      - adminer
    restart: on-failure
    networks:
      - piwinet

  piwibo-wsclient:
    <<: *php-env
    image: php-container
    restart: unless-stopped
    command:
      - php
      - app/console
      - websocket:client
      - ws://websocket:9090/ws
      - realm
      - system
    volumes:
      - .:/var/www/html
      - ws_cache:/var/www/html/var/cache
    depends_on:
      - database
      - mailhog
      - adminer
      - piwibo-php
    networks:
      - piwinet

  piwibo-scheduler:
    <<: *php-env
    image: php-container
    restart: unless-stopped
    command:
      - php
      - app/console
      - jms-job-queue:schedule
      - --env=dev
    volumes:
      - .:/var/www/html
      - sched_cache:/var/www/html/var/cache
    depends_on:
      - database
      - mailhog
      - adminer
      - piwibo-php
    networks:
      - piwinet

  piwibo-jobs:
    <<: *php-env
    image: php-container
    restart: unless-stopped
    command:
      - php
      - app/console
      - jms-job-queue:run
      - --env=dev
    volumes:
      - .:/var/www/html
      - job_cache:/var/www/html/var/cache
    depends_on:
      - database
      - mailhog
      - adminer
      - piwibo-php
    networks:
      - piwinet

  piwibo-web:
    build:
      context: .
      target: webservice
    ports:
      - 81:80
    volumes:
      - .:/var/www/html
    environment:
      - ENVIRONMENT=dev
      - PHPHOST=piwibo-php
      - PHPPORT=9000
      - TIMEZONE=Etc/GMT+4
      - APPHOST=http://localhost
    depends_on:
      - piwibo-php
    restart: always
    networks:
      - piwinet

#  websocket:
#    build:
#      context: ./websocket
#      target: websocket
#    environment:
#    - URL=0.0.0.0
#    - PORT=9090
#    - WAMP_PORT=9092
#    - REALM=realm
#    - JWT_SECRET=YourSampleKeyHere
#    - REDIS_URL=tcp://redis:6379
#    - REDIS_CODE=dev
#    volumes:
#    - ./websocket:/var/www/html/
#    ports:
#    - 83:9090
#    networks:
#    - piwinet

#  wallet:
#    image: registry.zmtsys.com/blockchain-wallet
#    environment:
#    - BLOCKCHAIN_SSH_USER=xpub
#    - BLOCKCHAIN_SSH_PASS=zmtsysxpub
#    expose:
#      - 22
#      - 3000
#    networks:
#    - piwinet

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - piwinet

  redisui:
    image: marian/rebrow
    ports:
      - "5001:5001"
    networks:
      - piwinet

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8087:8080
    networks:
      - piwinet

volumes:
  database:
  uploads:
  bo_cache:
  job_cache:
  sched_cache:
  ws_cache:

networks:
  piwinet:
    external: true
