version: "3.4"
services:
  php:
    build:
      context: ../
      dockerfile: $PWD/docker/php/Dockerfile
      target: prod
    volumes:
    - ../:/var/www/html
    - uploads:/uploads
    environment:
    - SYMFONY_ENV=dev
    - DATABASE_HOST=database
    - DATABASE_NAME=backoffice
    - DATABASE_USER=backoffice
    - DATABASE_PASSWORD_FILE=/run/secrets/dbpw
    - ECOPAYZ_TEST_MODE=true
    - BC_KEY=
    - BC_WALLET_URL=http://wallet:3000
    - BC_XPUB__HOST=wallet
    - BC_XPUB__USER=www
    - BC_XPUB__PASSWORD=admin.123
    secrets:
    - env
    - dbpw

  nginx:
    build:
      context: ../
      dockerfile: $PWD/docker/php/Dockerfile
      target: webservice
    environment:
    - PHPHOST=php
    - PHPPORT=9000
    volumes:
    - ../:/var/www/html

  wallet:
    build:
      context: .
      dockerfile: $PWD/docker/wallet/Dockerfile
    environment:
    - SSH_USER=www
    - SSH_PASS=admin.123
    - WALLET_PORT=3000

  database:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - database:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/dbrootpw
    - MYSQL_PASSWORD_FILE=/run/secrets/dbpw
    - MYSQL_DATABASE=backoffice
    - MYSQL_USER=backoffice
    secrets:
    - dbpw
    - dbrootpw

  mailhog:
    image: mailhog/mailhog
    command:
      - "-smtp-bind-addr"
      - "0.0.0.0:25"
    user: root

  adminer:
    image: adminer
    ports:
    - 9080:8080

volumes:
  database:
  uploads:

secrets:
  env:
    file: $PWD/secrets/env
  dbrootpw:
    file: $PWD/secrets/dbrootpw
  dbpw:
    file: $PWD/secrets/dbpw
