api_brokerage.delete_sync_id:
    path: brokerage/remove-sync-id
    defaults:
        _controller: BrokerageBundle:Brokerage:removeSyncId
    methods: [POST]

api_brokerage.post_bets:
    path: brokerage/post-bets
    defaults:
        _controller: BrokerageBundle:Brokerage:postBets
    methods: [POST]

api_brokerage.update_bet:
    path: brokerage/update-bet
    defaults:
        _controller: BrokerageBundle:Brokerage:updateBet
    methods: [POST]

api_brokerage.update_bet_details_by_event:
    path: brokerage/update-bet-details-by-event
    defaults:
        _controller: BrokerageBundle:Brokerage:updateBetDetailsByEvent
    methods: [POST]

api_brokerage.void_bet:
    path: brokerage/void-bet
    defaults:
        _controller: BrokerageBundle:Brokerage:voidBet
    methods: [POST]

api_brokerage.void_bets_by_event:
    path: brokerage/void-bets-by-event
    defaults:
        _controller: BrokerageBundle:Brokerage:voidBetsByEvent
    methods: [POST]

api_dwl.add_winloss_item:
    path: brokerage/dwl/add-winloss-item
    defaults:
        _controller: BrokerageBundle:Brokerage:addWinLossItem
    methods: [POST]

api_dwl.update_winloss_item:
    path: brokerage/dwl/update-winloss-item
    defaults:
        _controller: BrokerageBundle:Brokerage:updateWinLossItem
    methods: [POST]

api_dwl.update_date_winloss_item:
    path: brokerage/dwl/update-date-winloss-item
    defaults:
        _controller: BrokerageBundle:Brokerage:updateDateWinLossItem
    methods: [POST]