services:
    brokerage.brokerage_manager:
        class: BrokerageBundle\Manager\BrokerageManager
        parent: app.base_manager
        arguments: [ "@logger" ]
    brokerage.winloss_manager:
        class: BrokerageBundle\Manager\WinLossManager
        parent: app.base_manager
        calls:
            - ['setBrokerage', ['@brokerage.brokerage_service']]
    brokerage.transaction_listener:
        class: BrokerageBundle\Listener\TransactionListener
        calls:
            - [ setContainer, [ "@service_container" ] ]
        tags:
            - { name: "kernel.event_listener", event: "transaction.saved", method: "onTransactionSaved" }
    brokerage.customer_product_repository:
        class: BrokerageBundle\Repository\CustomerProductRepository
        factory_service: doctrine # this is an instance of Registry
        factory_method: getRepository
        arguments: [ "@doctrine.orm.entity_manager", "DbBundle\\Entity\\CustomerProduct" ]

    brokerage.brokerage_service:
        class: BrokerageBundle\Service\Brokerage
    brokerage.recompute_dwl_service:
        class: BrokerageBundle\Service\RecomputeDwlService
        calls:
            - ['setMemberProductRepository', ['@=service("doctrine").getRepository("DbBundle\\\Entity\\\CustomerProduct")']]
            - ['setTransactionRepository', ['@=service("doctrine").getRepository("DbBundle\\\Entity\\\Transaction")']]
            - ['setSubTransactionRepository', ['@=service("doctrine").getRepository("DbBundle\\\Entity\\\SubTransaction")']]
            - ['setAuditRepository', ['@=service("doctrine").getRepository("DbBundle\\\Entity\\\AuditRevision")']]
            - ['setDWLRepository', ['@=service("doctrine").getRepository("DbBundle\\\Entity\\\DWL")']]
            - ['setCommissionManager', ['@commission.manager']]
            - ['setTransactionManager', ['@transaction.manager']]
            - ['setEntityManager', ['@=service("doctrine").getManager("default")']]
    brokerage.sync_service:
        class: BrokerageBundle\Service\BrokerageSyncService
        calls:
            - ['setMemberProductRepository', ['@=service("doctrine").getRepository("DbBundle\\\Entity\\\CustomerProduct")']]
            - ['setDwlRepository', ['@=service("doctrine").getRepository("DbBundle\\\Entity\\\DWL")']]
            - ['setSubTransactionRepository', ['@=service("doctrine").getRepository("DbBundle\\\Entity\\\SubTransaction")']]
            - ['setTransactionManager', ['@transaction.manager']]
            - ['setRecomputeDwlService', ['@brokerage.recompute_dwl_service']]
            - ['setCommissionManager', ['@commission.manager']]
            - ['setEntityManager', ['@=service("doctrine").getManager("default")']]
            - ['setCommissionPeriodRepository', ['@=service("doctrine").getRepository("DbBundle\\\Entity\\\CommissionPeriod")']]
            - ['setTokenStorage', ['@security.token_storage']]
            - ['setKernelEnvironment', ['@=service("kernel").getEnvironment()']]