imports:
    - { resource: widgets.yml }
services:
    dwl.manager:
        class: DWLBundle\Manager\DWLManager
        parent: app.base_manager

    # form type
    dwl.form_type.dwl_upload_type:
        class: DWLBundle\Form\DWLUploadType
        arguments: [ "@doctrine", "@router" ]
        tags:
            - { name: form.type }

    # validator
    dwl.validator.dwl:
        class: DWLBundle\Validator\DWLValidator
        arguments: [ "@doctrine" ]
        tags:
            - { name: validator.constraint_validator, alias: dwl.validator.dwl }

    dwl.file_process.service:
        class: DWLBundle\Service\DWLFileProcessService
        calls:
            - [ "setContainer", ["@service_container"] ]
        shared: false

    dwl.submit.service:
        class: DWLBundle\Service\DWLSubmitService
        calls:
            - [ "setContainer", ["@service_container"] ]
        shared: false

    dwl.file_generator.service:
        class: DWLBundle\Service\DWLFileGeneratorService
        calls:
            - [ "setContainer", ["@service_container"] ]
        shared: false

    dwl.transaction_repository:
        class: DWLBundle\Repository\TransactionRepository
        lazy: true
        arguments: [ "@doctrine.orm.entity_manager"]