DbBundle\Entity\DWL:
    #constraints:
    #    - Callback: [DWLBundle\Validator]
    properties:
        id:
            - IsNull:
                groups: ['default']
                payload: {severity: "error"}
                message: dwl.exists
        product:
            - NotBlank:
                groups: ['default']
        currency:
            - NotBlank:
                groups: ['default']
        date:
            - NotBlank:
                groups: ['default']
            - Date:
                groups: ['default']
    
DWLBundle\Entity\DWLItem:
    constraints:
        - Callback:
            callback: validate
            groups: ['default']
    properties:
        dwl:
            - NotNull:
                groups: ['default']
        customerProduct:
            - NotNull:
                groups: ['default']
        username:
            - NotNull:
                groups: ['default']
            - NotBlank:
                groups: ['default']
        turnover:
            - NotNull:
                groups: ['default']
            - NotBlank:
                groups: ['default']
            - AppBundle\Validator\Constraints\IsNumeric:
                groups: ['default']
        gross:
            - NotNull:
                groups: ['default']
            - NotBlank:
                groups: ['default']
            - AppBundle\Validator\Constraints\IsNumeric:
                groups: ['default']
        winLoss:
            - NotNull:
                groups: ['default']
            - NotBlank:
                groups: ['default']
            - AppBundle\Validator\Constraints\IsNumeric:
                groups: ['default']
        commission:
            - NotNull:
                groups: ['default']
            - NotBlank:
                groups: ['default']
            - AppBundle\Validator\Constraints\IsNumeric:
                groups: ['default']
        amount:
            - NotNull:
                groups: ['default']
            - NotBlank:
                groups: ['default']
            - AppBundle\Validator\Constraints\IsNumeric:
                groups: ['default']
        updatedAt:
            - NotNull:
                groups: ['default']
            - NotBlank:
                groups: ['default']
            - Date:
                groups: ['default']
        version:
            - NotNull:
                groups: ['default']
            - NotBlank:
                groups: ['default']
            - AppBundle\Validator\Constraints\IsNumeric:
                groups: ['default']
            