services:
    widget.dwl_search:
        class: DWLBundle\Widget\DwlSearchWidget
        parent: app.widget_abstract
        calls:
            - [ 'setType', ['dwlSearch'] ]
        shared: false
        lazy: true
        tags:
            - { name: app.widget, widget_name: dwlSearch }
