services:
    zendesk.api_manager:
        class: ZendeskBundle\Manager\APIManager
        arguments:
            - '%zendesk_subdomain%'
        calls:
            - [setContainer, ["@service_container"]]
            - [setApiBase, ['%zendesk_api_base%']]
            - [setAuth, ['%zendesk_security_type%', '%zendesk_security_options%']]
            
    zendesk.base_manager:
        abstract: true
        calls:
            - [ 'setContainer', ['@service_container'] ]
            
    zendesk.view_manager:
        class: ZendeskBundle\Manager\ViewManager
        parent: zendesk.base_manager
        
    zendesk.ticket_manager:
        class: ZendeskBundle\Manager\TicketManager
        parent: zendesk.base_manager
        
    zendesk.user_manager:
        class: ZendeskBundle\Manager\UserManager
        parent: zendesk.base_manager