imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

doctrine:
    orm:
        metadata_cache_driver: apcu
        result_cache_driver: apcu
        query_cache_driver: apcu

monolog:
    handlers:
        main:
            formatter: app.monolog_formatter
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels: ['!blockchain_callback', '!blockchain_request']
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!blockchain_callback', '!blockchain_request']
        console:
            type:  console
            channels: ['!blockchain_callback', '!blockchain_request']
        dwl_submit:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_%upload_dwl_filename%"
            channels: ["dwl_submit"]
        slack:
            formatter: app.monolog_formatter
            type: slack
            token: "%slack.token%"
            channel: "%slack.channel%"
            bot_name: zmtsys
            level: critical
            use_attachment: true
            use_short_attachment: true
            include_extra: true
            channels: ['!blockchain_callback', '!blockchain_request']

