imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            formatter: app.monolog_formatter
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!event', '!blockchain_callback', '!blockchain_request']
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine", '!blockchain_callback', '!blockchain_request']
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]
        dwl_submit:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_%upload_dwl_filename%"
            channels: ["dwl_submit"]
        slack:
            formatter: app.monolog_formatter
            type: slack
            token: "%slack.token%"
            channel: "%slack.channel%"
            bot_name: zmtsys
            level: critical
            use_attachment: true
            use_short_attachment: true
            include_extra: true
            channels: ['!blockchain_callback', '!blockchain_request']

assetic:
    use_controller: false

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
            hosts: ['^api\.']

#doctrine:
    #orm:
    #    query_cache_driver:
    #        type: file_system
    #        cache_provider: file_cache
    #    metadata_cache_driver:
    #        type: file_system
    #        cache_provider: file_cache
    #    result_cache_driver:
    #        type: file_system
    #        cache_provider: file_cache

#doctrine_cache:
#    providers:
#        file_cache:
#            file_system:
#                extension: php
#                directory: "%kernel.root_dir%/cache/dev_doctrine"
#                #umask: 770
