imports:
    - { resource: widgets.yml }
services:
    TransactionBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        calls:
            - ['setContainer', ['@service_container']]

    transaction.manager:
        class: TransactionBundle\Manager\TransactionManager
        autowire: true
        autoConfig: true
        parent: app.base_manager
        calls:
            - ['setMemberRunningCommissionRepository', ['@=service("doctrine").getRepository("DbBundle\\Entity\\MemberRunningCommission")']]
            - ['setMemberRunningRevenueShareRepository', ['@=service("doctrine").getRepository("DbBundle\\Entity\\MemberRunningRevenueShare")']]
            - ['setCommissionPeriodRepository', ['@=service("doctrine").getRepository("DbBundle\\Entity\\CommissionPeriod")']]
    TransactionBundle\Manager\TransactionManager: "@transaction.manager"
    # form type
    transaction.form_type.bonus:
        class: TransactionBundle\Form\BonusType
        arguments: [ "@doctrine", "@router" ]
        tags:
            - { name: form.type }

    transaction.form_type.sub_transaction:
        class: TransactionBundle\Form\SubTransactionType
        arguments: [ "@doctrine" ]
        tags:
            - { name: form.type }

    transaction.form_type.transaction:
        class: TransactionBundle\Form\TransactionType
        arguments: [ "@doctrine", "@router", "@app.setting_manager", "@jms_serializer", "@member.manager" ]
        tags:
            - { name: form.type }

    transaction.workflow:
        factory: [TransactionBundle\Factory\TransactionWorkflowFactory, "generateTransactionWorkflow"]
        arguments: ['@app.setting_manager', '@event_dispatcher']

    transaction.process_subscriber:
        class: TransactionBundle\EventHandler\TransactionProcessSubscriber
        calls:
            - [ 'setContainer', ['@service_container'] ]
        tags:
            - { name: kernel.event_subscriber }

    transaction.transaction_subscriber_for_websocket:
        class: TransactionBundle\EventHandler\TransactionSubscriberForWebsocket
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_subscriber }
            
    transaction.decline.service:
        class: TransactionBundle\Service\TransactionDeclineService
        autowire: true
        autoconfigure: true
        calls:
            - [ "setContainer", ["@service_container"] ]
        shared: false

    transaction.lock.service:
        class: TransactionBundle\Service\TransactionBitcoinLockRateService
        calls:
            - [ "setContainer", ["@service_container"] ]
        shared: false

    TransactionBundle\Service\DeclineTransactionService:
        autowire: true
        autoconfigure: true
        public: false

    TransactionBundle\Command\:
        resource: '../../Command/'
        autowire: true
        autoconfigure: true
        public: false
        tags:
            - { name: 'console.command' }