ApiBundle\Request\Transaction\Meta\Bitcoin\BitcoinRateDetail:
  constraints:
    - Callback: [ApiBundle\Validator\Bitcoin\BitcoinValidatorCallback, validateRangeAmount]
  getters:
    rangeStart:
      - NotBlank: ~
      - Regex:
          pattern: '/^[0-9]+(\.[0-9]{1,})?$/'
          match: true
    rangeEnd:
      - NotBlank: ~
      - Regex:
          pattern: '/^[0-9]+(\.[0-9]{1,})?$/'
          match: true
    adjustment:
      - NotBlank: ~
      - Regex:
          pattern: '/^[0-9]+(\.[0-9]{1,})?$/'
          match: true
    adjustmentType:
      - Choice: ['fixed', 'percentage']

ApiBundle\Request\Transaction\Meta\Bitcoin\BitcoinPayment:
  group_sequence_provider: true
  constraints:
    - Callback:
        callback: [ApiBundle\Validator\Bitcoin\BitcoinValidatorCallback, validateConvertedAmount]
        groups: [afterBlank]
    - ApiBundle\Validator\Bitcoin\BitcoinTransactionConstraint: ~
  getters:
    blockchainRate:
      - NotBlank: ~
      - NotEqualTo:
          value: 0
          groups: [afterBlank]
      - Regex:
          pattern: '/^[0-9]+(\.[0-9]{1,})?$/'
          match: true
          groups: [afterBlank]
    rate:
      - NotBlank: ~
      - NotEqualTo:
          value: 0
          groups: [afterBlank]
      - Regex:
          pattern: '/^[0-9]+(\.[0-9]{1,})?$/'
          match: true
          groups: [afterBlank]
      - Callback:
          callback: [ApiBundle\Validator\Bitcoin\BitcoinValidatorCallback, validateRate]
          groups: [correctRate]
    rateDetail:
      - NotNull: ~
      - Valid: ~

ApiBundle\Request\Transaction\Meta\Bitcoin\BitcoinProductPayment:
  getters:
    bitcoin:
      - NotBlank: ~
      - NotEqualTo:
          value: 0
      - Regex:
          pattern: '/^[0-9]+(\.[0-9]{1,})?$/'
          match: true