ApiBundle\Request\Transaction\DepositRequest:
  group_sequence_provider: true
  getters:
    paymentOptionType:
      - NotBlank: ~
      - AppBundle\Validator\Constraints\Exists:
          entityClass: DbBundle\Entity\PaymentOption
          valuePath: value
          column: code
          ignoreNull: false
    products:
      - Count:
          min: 1
          minMessage: You should add atleast one product
      - Valid: ~
    customerFee:
      - NotBlank: ~
    companyFee:
      - NotBlank: ~
    meta:
      - Valid: ~