ApiBundle\Request\Transaction\DepositRequest:
  constraints:
    - ApiBundle\Validator\UniqueCustomerPaymentOptionEmailConstraint: { groups: [withEmail] }
  group_sequence_provider: true
  getters:
    paymentOptionType:
      - NotBlank: ~
#      - AppBundle\Validator\Constraints\Exists:
#          entityClass: DbBundle\Entity\PaymentOption
#          valuePath: value
#          column: code
#          ignoreNull: false
    products:
      - Count:
          min: 1
          minMessage: You should add atleast one product
    customerFee:
      - NotBlank: ~
    companyFee:
      - NotBlank: ~
    email:
      - NotNull:
          message: "Email cannot be empty"
          groups: [withEmail]
      - Email:
          message: "Invalid Email"
          groups: [withEmail]
