services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  PinnacleBundle\EventHandler\:
    resource: '../../EventHandler/'
    tags:
      - { name: kernel.event_subscriber }
  PinnacleBundle\Validator\PinnacleHasEnoughBalanceConstraintValidator:
    tags:
      - { name: validator.constraint_validator }
  PinnacleBundle\Service\PinnacleService:
    arguments:
      $apiUrl: '%pinnacle_api_url%'
      $agentCode: '%pinnacle_agent_code%'
      $agentKey: '%pinnacle_api_agent_key%'
      $secretKey: '%pinnacle_api_secret_key%'
      $logger: '@monolog.logger.pinnacle'