services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  PinnacleBundle\EventHandler\:
    resource: '../../EventHandler/'
    tags:
      - { name: kernel.event_subscriber }
