services:
    member.form_type.member_banner:
        class: ApiBundle\Form\Member\MemberBannerType
        arguments: ["@doctrine", "@app.setting_manager"]
        tags:
            - { name: form.type }

    ApiBundle\Form\MemberProduct\MemberProductType:
        arguments:
            - '@=service("doctrine").getRepository("DbBundle\\Entity\\Product")'
        tags:
            - { name: form.type }