services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    ApiBundle\RequestHandler\:
        resource: '../../RequestHandler'
        lazy: true
    ApiBundle\RequestHandler\AuthHandler:
        arguments:
            $jwtKey: "%jwt_key%"

    api.member.create_banner.request_handler: '@ApiBundle\RequestHandler\CreateMemberBannerRequestHandler'
    api.member_product.create.request_handler: '@ApiBundle\RequestHandler\CreateMemberProductRequestHandler'
