api_me:
  resource: "./routes/me.yml"

api_members:
  resource: "./routes/member.yml"
  prefix:   member/

api_affiliate:
  resource: "./routes/affiliate.yml"
  prefix:   affiliate/

api_2fa:
  resource: "./routes/2fa.yml"
  prefix: 2fa/

api_auth:
  resource: "./routes/auth.yml"
  prefix: auth/

api_setting:
  resource: "./routes/setting.yml"
  prefix: setting/

api_country:
  resource: "./routes/country.yml"

api_paymentoption:
  resource: "./routes/paymentoption.yml"