DbBundle\Entity\AuditRevision:
    exclusion_policy: ALL
    properties:
        clientIp:
            expose: true
        timestamp:
            expose: true
            type: DateTime<'c'>
        user:
            expose: true
        logs:
            type: array<DbBundle\Entity\AuditRevisionLog>