DbBundle\Entity\CommissionPeriod:
    exclusion_policy: ALL
    properties:
        dwlDateFrom:
            expose: true
            type: DateTime<'Y-m-d'>
            groups: ['Default', 'periodBalance']
        dwlDateTo:
            expose: true
            type: DateTime<'Y-m-d'>
            groups: ['Default', 'periodBalance']
        payoutAt:
            expose: true
            groups: ['Default', 'periodBalance']
        status:
            expose: true
            groups: ['Default', 'periodBalance']
        revenueShareStatus:
            expose: true
            groups: ['Default', 'periodBalance']
        dwlStatus:
            expose: true
            groups: ['Default', 'periodBalance']
        dwlUpdatedAt:
            expose: true
            groups: ['Default', 'periodBalance']
        updatedAt:
            expose: true
            groups: ['Default', 'periodBalance']