DbBundle\Entity\CustomerProduct:
    exclusion_policy: ALL
    xml_root_name: customerProduct
    properties:
        id:
            expose: true
        userName:
            expose: true
            groups: ['Default', 'request_list']
        product:
            expose: true
            groups: ['Default', 'request_list']
        balance:
            expose: true
        isActive:
            expose: true
        details:
            expose: true
        customer:
            expose: true
            groups: ['request_list']
        requestedAt:
            expose: true
            groups: ['Default', 'request_list']
    virtual_properties:
        isRequestedToday:
            expose: true
            serialized_name: is_requested_today
            groups: ['API']
        username:
            exp: object.getUserName()
            expose: true
            type: string
        getCurrency:
            exp: object.getCustomer().getCurrency()
            type: DbBundle\Entity\Currency
            expose: true
            serialized_name: currency
        updatedAt:
            exp: "object.getUpdatedAt() === null ? object.getCreatedAt() : object.getUpdatedAt()"
            type: DateTime
            expose: true
