DbBundle\Entity\DWL:
    exclusion_policy: ALL
    properties:
        createdAt:
            type: DateTime<'Y-m-d H:i:s'>
            expose: true
        currency:
            type: DbBundle\Entity\Currency
            expose: true
        date:
            type: DateTime<'Y-m-d H:i:s'>
            expose: true
        details:
            type: array
            expose: true
        product:
            type: DbBundle\Entity\Product
            expose: true
        status:
            type: int
            expose: true
        updatedAt:
            type: DateTime<'Y-m-d H:i:s'>
            expose: true
        version:
            expose: true
    virtual_properties:
        encodedUpdatedAt:
            type: string
            exp: object.getEncodedUpdatedAt()
            expose: true
            serialized_name: encodedUpdatedAt
        statusText:
            exp: object.getStatusAsText()
            type: string
            expose: true
            serialized_name: statusText
        canBeExported:
            exp: object.canBeExported()
            type: boolean
            expose: true
            serialized_name: canBeExported
            