SET time_zone = '+00:00';

INSERT INTO `user` (`user_id`, `user_created_by`, `user_group_id`, `user_username`, `user_password`, `user_email`, `user_phone_number`, `user_type`, `user_signup_type`, `user_is_active`, `user_roles`, `user_deleted_at`, `user_zendesk_id`, `user_key`, `user_activation_code`, `user_activation_sent_timestamp`, `user_activation_timestamp`, `user_created_at`, `user_updated_by`, `user_updated_at`, `user_preferences`, `user_reset_password_code`, `user_reset_password_sent_timestamp`) VALUES
(1,	NULL,	NULL,	'admin',	'$2y$12$RyTY5zbg0F1YxynNzA8qR.ZlZqh2TSTjUM5Wug2RVxZgVlQPCQdvu',	'admin@localhost.com',	NULL,	2,	2,	1,	'{\"ROLE_ADMIN\": 2, \"ROLE_SUPER_ADMIN\": 2}',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NOW(),	NULL,	NOW(),	'{\"lastLoginIP\": \"192.168.48.1\"}',	NULL,	NULL);

INSERT INTO `currency` (`currency_id`, `currency_updated_by`, `currency_code`, `currency_name`, `currency_rate`, `currency_created_by`, `currency_created_at`, `currency_updated_at`) VALUES
(1,	NULL,	'EUR',	'Euro',	1.0000000000,	1,	NOW(),	NULL);

INSERT INTO `country` (`country_id`, `country_currency_id`, `country_code`, `country_name`, `tags`, `country_created_by`, `country_created_at`, `country_updated_by`, `country_updated_at`, `country_phone_code`) VALUES
(1,	NULL,	'AF',	'Afghanistan',	'null',	1,	NOW(),	1,	NOW(),	'+93'),
(2,	NULL,	'AL',	'Albania',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+355'),
(3,	NULL,	'DZ',	'Algeria',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+213'),
(4,	NULL,	'AS',	'American Samoa',	'null',	1,	NOW(),	1,	NOW(),	'+1684'),
(5,	NULL,	'AD',	'Andorra',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+376'),
(6,	NULL,	'AO',	'Angola',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+244'),
(7,	NULL,	'AI',	'Anguilla',	'null',	1,	NOW(),	1,	NOW(),	'+1264'),
(8,	NULL,	'AQ',	'Antarctica',	'null',	1,	NOW(),	1,	NOW(),	'+672'),
(9,	NULL,	'AG',	'Antigua and Barbuda',	'null',	1,	NOW(),	1,	NOW(),	'+1268'),
(10,	NULL,	'AR',	'Argentina',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+54'),
(11,	NULL,	'AM',	'Armenia',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+374'),
(12,	NULL,	'AW',	'Aruba',	'null',	1,	NOW(),	1,	NOW(),	'+297'),
(13,	NULL,	'AU',	'Australia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+61'),
(14,	NULL,	'AT',	'Austria',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+43'),
(15,	NULL,	'AZ',	'Azerbaijan',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+994'),
(16,	NULL,	'BS',	'Bahamas',	'null',	1,	NOW(),	1,	NOW(),	'+1242'),
(17,	NULL,	'BH',	'Bahrain',	'null',	1,	NOW(),	1,	NOW(),	'+973'),
(18,	NULL,	'BD',	'Bangladesh',	'null',	1,	NOW(),	1,	NOW(),	'+880'),
(19,	NULL,	'BB',	'Barbados',	'null',	1,	NOW(),	1,	NOW(),	'+1246'),
(20,	NULL,	'BY',	'Belarus',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+375'),
(21,	NULL,	'BE',	'Belgium',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+32'),
(22,	NULL,	'BZ',	'Belize',	'null',	1,	NOW(),	1,	NOW(),	'+501'),
(23,	NULL,	'BJ',	'Benin',	'null',	1,	NOW(),	1,	NOW(),	'+229'),
(24,	NULL,	'BM',	'Bermuda',	'null',	1,	NOW(),	1,	NOW(),	'+1441'),
(25,	NULL,	'BT',	'Bhutan',	'null',	1,	NOW(),	1,	NOW(),	'+975'),
(26,	NULL,	'BO',	'Bolivia',	'null',	1,	NOW(),	1,	NOW(),	'+591'),
(27,	NULL,	'BA',	'Bosnia and Herzegovina',	'null',	1,	NOW(),	1,	NOW(),	'+387'),
(28,	NULL,	'BW',	'Botswana',	'null',	1,	NOW(),	1,	NOW(),	'+267'),
(29,	NULL,	'BV',	'Bouvet Island',	'null',	1,	NOW(),	1,	NOW(),	''),
(30,	NULL,	'BR',	'Brazil',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+55'),
(31,	NULL,	'IO',	'British Indian Ocean Territory',	'null',	1,	NOW(),	1,	NOW(),	'+246'),
(32,	NULL,	'BN',	'Brunei Darussalam',	'null',	1,	NOW(),	1,	NOW(),	'+673'),
(33,	NULL,	'BG',	'Bulgaria',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+359'),
(34,	NULL,	'BF',	'Burkina Faso',	'null',	1,	NOW(),	1,	NOW(),	'+226'),
(35,	NULL,	'BI',	'Burundi',	'null',	1,	NOW(),	1,	NOW(),	'+257'),
(36,	NULL,	'KH',	'Cambodia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+855'),
(37,	NULL,	'CM',	'Cameroon',	'null',	1,	NOW(),	1,	NOW(),	'+237'),
(38,	NULL,	'CA',	'Canada',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+1'),
(39,	NULL,	'CV',	'Cape Verde',	'null',	1,	NOW(),	1,	NOW(),	'+238'),
(40,	NULL,	'KY',	'Cayman Islands',	'null',	1,	NOW(),	1,	NOW(),	'+345'),
(41,	NULL,	'CF',	'Central African Republic',	'null',	1,	NOW(),	1,	NOW(),	'+236'),
(42,	NULL,	'TD',	'Chad',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+235'),
(43,	NULL,	'CL',	'Chile',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+56'),
(44,	NULL,	'CN',	'China',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+86'),
(45,	NULL,	'CX',	'Christmas Island',	'null',	1,	NOW(),	1,	NOW(),	'+61'),
(46,	NULL,	'CC',	'Cocos (Keeling) Islands',	'null',	1,	NOW(),	1,	NOW(),	'+61'),
(47,	NULL,	'CO',	'Colombia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+57'),
(48,	NULL,	'KM',	'Comoros',	'null',	1,	NOW(),	1,	NOW(),	'+269'),
(49,	NULL,	'CG',	'Congo',	'null',	1,	NOW(),	1,	NOW(),	'+242'),
(50,	NULL,	'CK',	'Cook Islands',	'null',	1,	NOW(),	1,	NOW(),	'+682'),
(51,	NULL,	'CR',	'Costa Rica',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+506'),
(52,	NULL,	'CI',	'Cote DIvoire',	'null',	1,	NOW(),	1,	NOW(),	'+225'),
(53,	NULL,	'HR',	'Croatia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+385'),
(54,	NULL,	'CU',	'Cuba',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+53'),
(55,	NULL,	'CY',	'Cyprus',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+537'),
(56,	NULL,	'CZ',	'Czech Republic',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+420'),
(57,	NULL,	'DK',	'Denmark',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+45'),
(58,	NULL,	'DJ',	'Djibouti',	'null',	1,	NOW(),	1,	NOW(),	'+253'),
(59,	NULL,	'DM',	'Dominica',	'null',	1,	NOW(),	1,	NOW(),	'+1767'),
(60,	NULL,	'DO',	'Dominican Republic',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+1849'),
(61,	NULL,	'TL',	'East Timor',	'null',	1,	NOW(),	1,	NOW(),	'+670'),
(62,	NULL,	'EC',	'Ecuador',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+593'),
(63,	NULL,	'EG',	'Egypt',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+20'),
(64,	NULL,	'SV',	'El Salvador',	'null',	1,	NOW(),	1,	NOW(),	'+503'),
(65,	NULL,	'GQ',	'Equatorial Guinea',	'null',	1,	NOW(),	1,	NOW(),	'+240'),
(66,	NULL,	'ER',	'Eritrea',	'null',	1,	NOW(),	1,	NOW(),	'+291'),
(67,	NULL,	'EE',	'Estonia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+372'),
(68,	NULL,	'ET',	'Ethiopia',	'null',	1,	NOW(),	1,	NOW(),	'+251'),
(69,	NULL,	'FK',	'Falkland Islands (Malvinas)',	'null',	1,	NOW(),	1,	NOW(),	'+500'),
(70,	NULL,	'FO',	'Faroe Islands',	'null',	1,	NOW(),	1,	NOW(),	'+298'),
(71,	NULL,	'FJ',	'Fiji',	'null',	1,	NOW(),	1,	NOW(),	'+679'),
(72,	NULL,	'FI',	'Finland',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+358'),
(73,	NULL,	'FR',	'France',	'[]',	1,	NOW(),	1,	NOW(),	'+33'),
(74,	NULL,	'FRM',	'France, Metropolitan',	'null',	1,	NOW(),	1,	NOW(),	''),
(75,	NULL,	'GF',	'French Guiana',	'null',	1,	NOW(),	1,	NOW(),	'+594'),
(76,	NULL,	'PF',	'French Polynesia',	'null',	1,	NOW(),	1,	NOW(),	'+689'),
(77,	NULL,	'TF',	'French Southern Territories',	'null',	1,	NOW(),	1,	NOW(),	''),
(78,	NULL,	'GA',	'Gabon',	'null',	1,	NOW(),	1,	NOW(),	'+241'),
(79,	NULL,	'GM',	'Gambia',	'null',	1,	NOW(),	1,	NOW(),	'+220'),
(80,	NULL,	'GE',	'Georgia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+995'),
(81,	NULL,	'DE',	'Germany',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+49'),
(82,	NULL,	'GH',	'Ghana',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+233'),
(83,	NULL,	'GI',	'Gibraltar',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+350'),
(84,	NULL,	'GR',	'Greece',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+30'),
(85,	NULL,	'GL',	'Greenland',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+299'),
(86,	NULL,	'GD',	'Grenada',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+1473'),
(87,	NULL,	'GP',	'Guadeloupe',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+590'),
(88,	NULL,	'GU',	'Guam',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+1671'),
(89,	NULL,	'GT',	'Guatemala',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+502'),
(90,	NULL,	'GN',	'Guinea',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+224'),
(91,	NULL,	'GW',	'Guinea-bissau',	'null',	1,	NOW(),	1,	NOW(),	'+245'),
(92,	NULL,	'GY',	'Guyana',	'null',	1,	NOW(),	1,	NOW(),	'+595'),
(93,	NULL,	'HT',	'Haiti',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+509'),
(94,	NULL,	'HM',	'Heard and Mc Donald Islands',	'null',	1,	NOW(),	1,	NOW(),	''),
(95,	NULL,	'HN',	'Honduras',	'null',	1,	NOW(),	1,	NOW(),	'+504'),
(96,	NULL,	'HK',	'Hong Kong',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+852'),
(97,	NULL,	'HU',	'Hungary',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+36'),
(98,	NULL,	'IS',	'Iceland',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+354'),
(99,	NULL,	'IN',	'India',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+91'),
(100,	NULL,	'ID',	'Indonesia',	'null',	1,	NOW(),	1,	NOW(),	'+62'),
(101,	NULL,	'IR',	'Iran',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+98'),
(102,	NULL,	'IQ',	'Iraq',	'null',	1,	NOW(),	1,	NOW(),	'+964'),
(103,	NULL,	'IE',	'Ireland',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+353'),
(104,	NULL,	'IL',	'Israel',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+972'),
(105,	NULL,	'IT',	'Italy',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+39'),
(106,	NULL,	'JM',	'Jamaica',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+1876'),
(107,	NULL,	'JP',	'Japan',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+81'),
(108,	NULL,	'JO',	'Jordan',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+962'),
(109,	NULL,	'KZ',	'Kazakhstan',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+77'),
(110,	NULL,	'KE',	'Kenya',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+254'),
(111,	NULL,	'KI',	'Kiribati',	'null',	1,	NOW(),	1,	NOW(),	'+686'),
(112,	NULL,	'KP',	'Korea (North)',	'null',	1,	NOW(),	1,	NOW(),	'+850'),
(113,	NULL,	'KR',	'Korea (South)',	'null',	1,	NOW(),	1,	NOW(),	'+82'),
(114,	NULL,	'KW',	'Kuwait',	'null',	1,	NOW(),	1,	NOW(),	'+965'),
(115,	NULL,	'KG',	'Kyrgyzstan',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+996'),
(116,	NULL,	'LA',	'Lao Peoples Democratic Republic',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+856'),
(117,	NULL,	'LV',	'Latvia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+371'),
(118,	NULL,	'LB',	'Lebanon',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+961'),
(119,	NULL,	'LS',	'Lesotho',	'null',	1,	NOW(),	1,	NOW(),	'+266'),
(120,	NULL,	'LR',	'Liberia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+231'),
(121,	NULL,	'LY',	'Libyan Arab Jamahiriya',	'null',	1,	NOW(),	1,	NOW(),	'+218'),
(122,	NULL,	'LI',	'Liechtenstein',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+423'),
(123,	NULL,	'LT',	'Lithuania',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+370'),
(124,	NULL,	'LU',	'Luxembourg',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+352'),
(125,	NULL,	'MO',	'Macau',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+853'),
(126,	NULL,	'MK',	'Macedonia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+389'),
(127,	NULL,	'MG',	'Madagascar',	'null',	1,	NOW(),	1,	NOW(),	'+261'),
(128,	NULL,	'MW',	'Malawi',	'null',	1,	NOW(),	1,	NOW(),	'+265'),
(129,	NULL,	'MY',	'Malaysia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+60'),
(130,	NULL,	'MV',	'Maldives',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+960'),
(131,	NULL,	'ML',	'Mali',	'null',	1,	NOW(),	1,	NOW(),	'+223'),
(132,	NULL,	'MT',	'Malta',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+356'),
(133,	NULL,	'MH',	'Marshall Islands',	'null',	1,	NOW(),	1,	NOW(),	'+692'),
(134,	NULL,	'MQ',	'Martinique',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+596'),
(135,	NULL,	'MR',	'Mauritania',	'null',	1,	NOW(),	1,	NOW(),	'+222'),
(136,	NULL,	'MU',	'Mauritius',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+230'),
(137,	NULL,	'YT',	'Mayotte',	'null',	1,	NOW(),	1,	NOW(),	'+262'),
(138,	NULL,	'MX',	'Mexico',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+52'),
(139,	NULL,	'FM',	'Micronesia',	'null',	1,	NOW(),	1,	NOW(),	'+691'),
(140,	NULL,	'MD',	'Moldova',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+373'),
(141,	NULL,	'MC',	'Monaco',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+377'),
(142,	NULL,	'MN',	'Mongolia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+976'),
(143,	NULL,	'MS',	'Montserrat',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+1664'),
(144,	NULL,	'MA',	'Morocco',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+212'),
(145,	NULL,	'MZ',	'Mozambique',	'null',	1,	NOW(),	1,	NOW(),	'+258'),
(146,	NULL,	'MM',	'Myanmar',	'[\"ac88-main\", \"Myanmar\"]',	1,	NOW(),	1,	NOW(),	'+95'),
(147,	NULL,	'NA',	'Namibia',	'null',	1,	NOW(),	1,	NOW(),	'+264'),
(148,	NULL,	'NR',	'Nauru',	'null',	1,	NOW(),	1,	NOW(),	'+674'),
(149,	NULL,	'NP',	'Nepal',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+977'),
(150,	NULL,	'NL',	'Netherlands',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+31'),
(151,	NULL,	'AN',	'Netherlands Antilles',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+599'),
(152,	NULL,	'NC',	'New Caledonia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+687'),
(153,	NULL,	'NZ',	'New Zealand',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+64'),
(154,	NULL,	'NI',	'Nicaragua',	'null',	1,	NOW(),	1,	NOW(),	'+505'),
(155,	NULL,	'NE',	'Niger',	'null',	1,	NOW(),	1,	NOW(),	'+227'),
(156,	NULL,	'NG',	'Nigeria',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+234'),
(157,	NULL,	'NU',	'Niue',	'null',	1,	NOW(),	1,	NOW(),	'+683'),
(158,	NULL,	'NF',	'Norfolk Island',	'null',	1,	NOW(),	1,	NOW(),	'+672'),
(159,	NULL,	'MP',	'Northern Mariana Islands',	'null',	1,	NOW(),	1,	NOW(),	'+1670'),
(160,	NULL,	'NO',	'Norway',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+47'),
(161,	NULL,	'OM',	'Oman',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+968'),
(162,	NULL,	'PK',	'Pakistan',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+92'),
(163,	NULL,	'PW',	'Palau',	'null',	1,	NOW(),	1,	NOW(),	'+680'),
(164,	NULL,	'PA',	'Panama',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+507'),
(165,	NULL,	'PG',	'Papua New Guinea',	'null',	1,	NOW(),	1,	NOW(),	'+675'),
(166,	NULL,	'PY',	'Paraguay',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+595'),
(167,	NULL,	'PE',	'Peru',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+51'),
(168,	NULL,	'PH',	'Philippines',	'null',	1,	NOW(),	1,	NOW(),	'+63'),
(169,	NULL,	'PN',	'Pitcairn',	'null',	1,	NOW(),	1,	NOW(),	'+872'),
(170,	NULL,	'PL',	'Poland',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+48'),
(171,	NULL,	'PT',	'Portugal',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+351'),
(172,	NULL,	'PR',	'Puerto Rico',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+1939'),
(173,	NULL,	'QA',	'Qatar',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+974'),
(174,	NULL,	'RE',	'Reunion',	'null',	1,	NOW(),	1,	NOW(),	'+262'),
(175,	NULL,	'RO',	'Romania',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+40'),
(176,	NULL,	'RU',	'Russian Federation',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+7'),
(177,	NULL,	'RW',	'Rwanda',	'null',	1,	NOW(),	1,	NOW(),	'+250'),
(178,	NULL,	'KN',	'Saint Kitts and Nevis',	'null',	1,	NOW(),	1,	NOW(),	'+1869'),
(179,	NULL,	'LC',	'Saint Lucia',	'null',	1,	NOW(),	1,	NOW(),	'+1758'),
(180,	NULL,	'VC',	'Saint Vincent and the Grenadines',	'null',	1,	NOW(),	1,	NOW(),	'+1784'),
(181,	NULL,	'WS',	'Samoa',	'null',	1,	NOW(),	1,	NOW(),	'+685'),
(182,	NULL,	'SM',	'San Marino',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+378'),
(183,	NULL,	'ST',	'Sao Tome and Principe',	'null',	1,	NOW(),	1,	NOW(),	'+239'),
(184,	NULL,	'SA',	'Saudi Arabia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+966'),
(185,	NULL,	'SN',	'Senegal',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+221'),
(186,	NULL,	'SC',	'Seychelles',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+248'),
(187,	NULL,	'SL',	'Sierra Leone',	'null',	1,	NOW(),	1,	NOW(),	'+232'),
(188,	NULL,	'SG',	'Singapore',	'null',	1,	NOW(),	1,	NOW(),	'+65'),
(189,	NULL,	'SK',	'Slovakia (Slovak Republic)',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+421'),
(190,	NULL,	'SI',	'Slovenia',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+386'),
(191,	NULL,	'SB',	'Solomon Islands',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+677'),
(192,	NULL,	'SO',	'Somalia',	'null',	1,	NOW(),	1,	NOW(),	'+252'),
(193,	NULL,	'ZA',	'South Africa',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+27'),
(194,	NULL,	'GS',	'South Georgia and the South Sandwich Islands',	'null',	1,	NOW(),	1,	NOW(),	'+500'),
(195,	NULL,	'ES',	'Spain',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+34'),
(196,	NULL,	'LK',	'Sri Lanka',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+94'),
(197,	NULL,	'SH',	'St. Helena',	'null',	1,	NOW(),	1,	NOW(),	'+290'),
(198,	NULL,	'PM',	'St. Pierre and Miquelon',	'null',	1,	NOW(),	1,	NOW(),	'+508'),
(199,	NULL,	'SD',	'Sudan',	'null',	1,	NOW(),	1,	NOW(),	'+249'),
(200,	NULL,	'SR',	'Suriname',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+597'),
(201,	NULL,	'SJ',	'Svalbard and Jan Mayen Islands',	'null',	1,	NOW(),	1,	NOW(),	'+47'),
(202,	NULL,	'SZ',	'Swaziland',	'null',	1,	NOW(),	1,	NOW(),	'+268'),
(203,	NULL,	'SE',	'Sweden',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+46'),
(204,	NULL,	'CH',	'Switzerland',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+41'),
(205,	NULL,	'SY',	'Syrian Arab Republic',	'null',	1,	NOW(),	1,	NOW(),	'+963'),
(206,	NULL,	'TW',	'Taiwan',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+886'),
(207,	NULL,	'TJ',	'Tajikistan',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+992'),
(208,	NULL,	'TZ',	'Tanzania',	'null',	1,	NOW(),	1,	NOW(),	'+255'),
(209,	NULL,	'TH',	'Thailand',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+66'),
(210,	NULL,	'TG',	'Togo',	'null',	1,	NOW(),	1,	NOW(),	'+228'),
(211,	NULL,	'TK',	'Tokelau',	'null',	1,	NOW(),	1,	NOW(),	'+690'),
(212,	NULL,	'TO',	'Tonga',	'null',	1,	NOW(),	1,	NOW(),	'+676'),
(213,	NULL,	'TT',	'Trinidad and Tobago',	'null',	1,	NOW(),	1,	NOW(),	'+1868'),
(214,	NULL,	'TN',	'Tunisia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+216'),
(215,	NULL,	'TR',	'Turkey',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+90'),
(216,	NULL,	'TM',	'Turkmenistan',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+993'),
(217,	NULL,	'TC',	'Turks and Caicos Islands',	'null',	1,	NOW(),	1,	NOW(),	'+1649'),
(218,	NULL,	'TV',	'Tuvalu',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+688'),
(219,	NULL,	'UG',	'Uganda',	'null',	1,	NOW(),	1,	NOW(),	'+256'),
(220,	NULL,	'UA',	'Ukraine',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+380'),
(221,	NULL,	'AE',	'United Arab Emirates',	'null',	1,	NOW(),	1,	NOW(),	'+971'),
(222,	NULL,	'GB',	'United Kingdom',	'null',	1,	NOW(),	1,	NOW(),	'+44'),
(223,	NULL,	'US',	'United States',	'null',	1,	NOW(),	1,	NOW(),	'+1'),
(224,	NULL,	'UM',	'United States Minor Outlying Islands',	'null',	1,	NOW(),	1,	NOW(),	''),
(225,	NULL,	'UY',	'Uruguay',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+598'),
(226,	NULL,	'UZ',	'Uzbekistan',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+998'),
(227,	NULL,	'VU',	'Vanuatu',	'null',	1,	NOW(),	1,	NOW(),	'+678'),
(228,	NULL,	'VA',	'Vatican City State (Holy See)',	'null',	1,	NOW(),	1,	NOW(),	'+379'),
(229,	NULL,	'VE',	'Venezuela',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+58'),
(230,	NULL,	'VN',	'Vietnam',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+84'),
(231,	NULL,	'VG',	'Virgin Islands British',	'null',	1,	NOW(),	1,	NOW(),	'+1284'),
(232,	NULL,	'VI',	'Virgin Islands U.S.',	'null',	1,	NOW(),	1,	NOW(),	'+1340'),
(233,	NULL,	'WF',	'Wallis and Futuna Islands',	'null',	1,	NOW(),	1,	NOW(),	'+681'),
(234,	NULL,	'EH',	'Western Sahara',	'null',	1,	NOW(),	1,	NOW(),	''),
(235,	NULL,	'YE',	'Yemen',	'null',	1,	NOW(),	1,	NOW(),	'+967'),
(236,	NULL,	'YU',	'Yugoslavia',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	''),
(237,	NULL,	'CD',	'Zaire',	'null',	1,	NOW(),	1,	NOW(),	'+243'),
(238,	NULL,	'ZM',	'Zambia',	'null',	1,	NOW(),	1,	NOW(),	'+260'),
(239,	NULL,	'ZW',	'Zimbabwe',	'null',	1,	NOW(),	1,	NOW(),	'+263'),
(240,	NULL,	'UKE',	'England',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+'),
(241,	NULL,	'ME',	'Montenegro',	'[\"ac88-main\", \"ac88-promo\"]',	1,	NOW(),	1,	NOW(),	'+382'),
(242,	NULL,	'RS',	'Serbia',	'[\"ac88-main\"]',	1,	NOW(),	1,	NOW(),	'+381');

INSERT INTO `setting` (`setting_id`, `setting_code`, `setting_value`) VALUES
(1,	'transaction.status',	'{\"1\": {\"label\": \"Requested\", \"start\": true, \"actions\": {\"3\": {\"class\": \"btn-success\", \"label\": \"Acknowledge\", \"status\": 4}}, \"amsLabel\": \"Requested\", \"editDate\": false, \"editFees\": false, \"editAmount\": false, \"editGateway\": false, \"editBonusAmount\": false}, \"2\": {\"end\": true, \"label\": \"Processed\", \"actions\": [], \"amsLabel\": \"Processed\", \"editDate\": false, \"editFees\": false, \"editAmount\": false, \"editGateway\": false, \"editBonusAmount\": false}, \"3\": {\"label\": \"Declined\", \"actions\": [], \"decline\": true, \"amsLabel\": \"Declined\", \"editDate\": false, \"editFees\": false, \"editAmount\": false, \"editGateway\": false, \"editBonusAmount\": false}, \"4\": {\"label\": \"Acknowledged\", \"actions\": [{\"class\": \"btn-success\", \"label\": \"Process\", \"status\": 2}, {\"class\": \"btn-danger\", \"label\": \"Decline\", \"status\": 3}], \"amsLabel\": \"Acknowledged\", \"editDate\": true, \"editFees\": true, \"editAmount\": true, \"editGateway\": true, \"editBonusAmount\": true}}'),
(2,	'transaction.paymentGateway',	'\"customer-group\"'),
(3,	'transaction.start',	'{\"admin\": 2, \"customer\": 1}'),
(25,	'currency.base',	'1'),
(97,	'maintenance.enabled',	'false'),
(98,	'transaction.equations',	'{\"dwl\": {\"totalAmount\": {\"equation\": \"x+y\", \"variables\": {\"x\": \"sum_products\", \"y\": \"total_customer_fee\"}}, \"customerAmount\": {\"equation\": \"x+y\", \"variables\": {\"x\": \"sum_products\", \"y\": \"total_customer_fee\"}}}, \"deposit\": {\"totalAmount\": {\"equation\": \"x+y\", \"variables\": {\"x\": \"sum_products\", \"y\": \"total_customer_fee\"}}, \"customerAmount\": {\"equation\": \"x\", \"variables\": {\"x\": \"sum_products\"}}}, \"transfer\": {\"totalAmount\": {\"equation\": \"x\", \"variables\": {\"x\": \"sum_withdraw_products\"}}, \"customerAmount\": {\"equation\": \"x\", \"variables\": {\"x\": \"sum_withdraw_products\"}}}, \"withdraw\": {\"totalAmount\": {\"equation\": \"x\", \"variables\": {\"x\": \"sum_products\"}}, \"customerAmount\": {\"equation\": \"x-y\", \"variables\": {\"x\": \"sum_products\", \"y\": \"total_customer_fee\"}}}, \"p2p_transfer\": {\"totalAmount\": {\"equation\": \"x\", \"variables\": {\"x\": \"sum_withdraw_products\"}}, \"customerAmount\": {\"equation\": \"x\", \"variables\": {\"x\": \"sum_withdraw_products\"}}}}'),
(99,	'counter',	'0'),
(100,	'transaction.list.filters',	'{\"pending\": {\"filters\": {\"voided\": \"\", \"excludeStatus\": [\"2\", \"3\"]}}}'),
(101,	'transaction.type',	'{\"start\": {\"dwl\": 2}, \"workflow\": {\"dwl\": {\"2\": {\"actions\": [{\"label\": \"approve\", \"status\": 2}]}}}}'),
(102,	'scheduler.task',	'{\"auto_decline\": {\"autoDecline\": true, \"minutesInterval\": 60}}'),
(103,	'referral.tools',	'{\"links\": {\"AO\": {\"urls\": {\"promotion\": \"https://www.asianodds88.com/register-promo.aspx/\", \"advertisement\": \"https://www.asianodds88.com/register.aspx/\"}, \"siteId\": 3}, \"DE\": {\"urls\": {\"promotion\": \"https://de.asianconnect88.com/promotion/acwelcome400-geschaftsbedingungen/\", \"advertisement\": \"https://de.asianconnect88.com/register/\"}, \"siteId\": 21}, \"EN\": {\"urls\": {\"promotion\": \"https://www.asianconnect88.com/promotion/acwelcome400-terms-and-conditions/\", \"advertisement\": \"https://www.asianconnect88.com/register/\"}, \"siteId\": 2}, \"ES\": {\"urls\": {\"promotion\": \"https://www.asianconect88.com/promociones/\", \"advertisement\": \"https://www.asianconect88.com/registro/\"}, \"siteId\": 22}, \"FR\": {\"urls\": {\"promotion\": \"https://ac0188.com/inscription/\", \"advertisement\": \"https://ac0188.com/inscription/\"}, \"siteId\": 18}}, \"piwikUrlKey\": \"pk_kwd\"}'),
(104,	'commission',	'{\"enable\": true, \"payout\": {\"days\": \"5\", \"time\": \"00:00\"}, \"period\": {\"day\": \"1\", \"every\": \"1\", \"frequency\": \"monthly\"}, \"startDate\": \"2018-06-29\", \"conditions\": [{\"field\": \"active_member\", \"value\": \">=5\"}]}'),
(106,	'origin',	'{\"origins\": [{\"url\": \"https://www.asianconnect88.com/\", \"code\": \"EN\", \"name\": \"https://www.asianconnect88.com\"}, {\"url\": \"https://asianconnect88.net/\", \"code\": \"EN\", \"name\": \"https://asianconnect88.net\"}, {\"url\": \"https://www.asianconnect888.com/\", \"code\": \"EN\", \"name\": \"https://www.asianconnect888.com\"}, {\"url\": \"https://fr.asianconnect88.com/\", \"code\": \"FR\", \"name\": \"https://fr.asianconnect88.com\"}, {\"url\": \"https://ac0808.com/\", \"code\": \"FR\", \"name\": \"https://ac0808.com\"}, {\"url\": \"https://ac0188.com/\", \"code\": \"FR\", \"name\": \"https://ac0188.com\"}, {\"url\": \"https://ac0288.com/\", \"code\": \"FR\", \"name\": \"https://ac0288.com\"}, {\"url\": \"https://de.asianconnect88.com/\", \"code\": \"DE\", \"name\": \"https://de.asianconnect88.com\"}, {\"url\": \"https://www.asianconnectde.com/\", \"code\": \"DE\", \"name\": \"https://www.asianconnectde.com\"}, {\"url\": \"https://www.asianconect88.com/\", \"code\": \"ES\", \"name\": \"https://www.asianconect88.com\"}, {\"url\": \"http://www.asianconnect08.com/\", \"code\": \"ES\", \"name\": \"http://www.asianconnect08.com\"}]}'),
(107,	'bitcoin.confirmations',	'[{\"num\": 0, \"label\": \"Pending confirmation\", \"transactionStatus\": \"1\"}, {\"num\": 1, \"label\": \"Pending confirmation\", \"transactionStatus\": \"1\"}, {\"num\": 2, \"label\": \"Pending confirmation\", \"transactionStatus\": \"1\"}, {\"num\": 3, \"label\": \"Confirmed\", \"transactionStatus\": \"4\"}]'),
(108,	'piwi247.session',	'{\"refreshSessionInterval\": \"720000\"}'),
(109,	'transaction.validate',	'{\"skrill\": {\"deposit\": {\"fee\": 0, \"max_amount\": 10000, \"min_amount\": 10}, \"withdraw\": {\"fee\": 0, \"max_amount\": 10000, \"min_amount\": 10}}, \"bitcoin\": {\"deposit\": {\"fee\": 0, \"max_amount\": 10000, \"min_amount\": 0.0001}, \"withdraw\": {\"fee\": 0, \"max_amount\": 10000, \"min_amount\": \"0.0001\"}}, \"neteller\": {\"deposit\": {\"fee\": 0, \"max_amount\": 10000, \"min_amount\": 10}, \"withdraw\": {\"fee\": 0, \"max_amount\": 10000, \"min_amount\": 10}}}'),
(110,	'bitcoin.setting.withdrawalConfiguration',	'[{\"min\": \"200\"}]'),
(113,	'bitcoin.setting',	'{\"configuration\": {\"autoDecline\": false, \"minutesInterval\": 20, \"maximumAllowedDeposit\": \"40\", \"minimumAllowedDeposit\": \"0.0001\"}, \"lockRatePeriodSetting\": {\"autoLock\": false, \"minutesLockDownInterval\": 20}, \"withdrawalConfiguration\": {\"maximumAllowedWithdrawal\": \"40\", \"minimumAllowedWithdrawal\": \"0.0001\"}}'),
(114,	'pinnacle',	'{\"product\": \"PINBET\"}');

INSERT INTO `product` (`product_id`, `product_code`, `product_name`, `product_is_active`, `product_deleted_at`, `product_created_by`, `product_created_at`, `product_updated_by`, `product_updated_at`, `product_logo_uri`, `product_url`, `product_details`) VALUES
(1,	'PINBET',	'PIN BET',	1,	NULL,	1,	NOW(),	NULL,	NULL,	NULL,	NULL, '{}');