SET time_zone = '+00:00';

INSERT INTO `payment_option` (`payment_option_code`, `payment_option_name`, `payment_option_fields`, `payment_option_image_uri`, `payment_option_is_active`, `payment_option_has_auto_decline`, `payment_option_sort`, `payment_option_created_by`, `payment_option_created_at`, `payment_option_updated_by`, `payment_option_updated_at`, `payment_mode`) VALUES
('BANK',	'Bank Account',	'[{\"code\": \"bank_name\", \"type\": \"text\", \"label\": \"Bank Name\", \"order\": null, \"isUnique\": false, \"isRequired\": false}, {\"code\": \"swift_code\", \"type\": \"text\", \"label\": \"Swift\", \"order\": null, \"isUnique\": false, \"isRequired\": false}, {\"code\": \"iban_number\", \"type\": \"text\", \"label\": \"IBAN\", \"order\": null, \"isUnique\": false, \"isRequired\": false}, {\"code\": \"bank_address\", \"type\": \"text\", \"label\": \"Bank Address\", \"order\": null, \"isUnique\": false, \"isRequired\": false}, {\"code\": \"notes\", \"type\": \"text\", \"label\": \"Notes\", \"order\": null, \"isUnique\": false, \"isRequired\": false}]',	NULL,	1,	0,	'',	1,	NOW(),	1,	NOW(),	'offline'),
('BITCOIN',	'Bitcoin Account',	'[{\"code\": \"account_id\", \"type\": \"text\", \"label\": \"Bitcoin ID\", \"order\": null, \"isUnique\": false, \"isRequired\": false}, {\"code\": \"email\", \"type\": \"text\", \"label\": \"Email\", \"order\": null, \"isUnique\": false, \"isRequired\": false}, {\"code\": \"notes\", \"type\": \"text\", \"label\": \"Notes\", \"order\": null, \"isUnique\": false, \"isRequired\": false}]',	NULL,	1,	0,	'',	1,	NOW(),	1,	NOW(),	'bitcoin'),
('ECOPAYZ',	'Ecopayz Account',	'[{\"code\": \"account_id\", \"type\": \"text\", \"label\": \"Account\", \"order\": null, \"isActive\": false}, {\"code\": \"email\", \"type\": \"text\", \"label\": \"Email\", \"order\": null, \"isActive\": false}, {\"code\": \"notes\", \"type\": \"text\", \"label\": \"Notes\", \"order\": null, \"isActive\": false}]',	NULL,	1,	1,	'',	NULL,	NOW(),	1,	NOW(),	'ecopayz'),
('NETELLER',	'Neteller Account',	'[{\"code\": \"account_id\", \"type\": \"text\", \"label\": \"Account\", \"order\": null}, {\"code\": \"email\", \"type\": \"text\", \"label\": \"Email\", \"order\": null}, {\"code\": \"notes\", \"type\": \"text\", \"label\": \"Notes\", \"order\": null}]',	NULL,	1,	1,	'',	1,	NOW(),	1,	NOW(),	'offline'),
('PAYPAL',	'Paypal Account',	'[{\"code\": \"account_id\", \"type\": \"text\", \"label\": \"Account\"}, {\"code\": \"email\", \"type\": \"text\", \"label\": \"Email\"}, {\"code\": \"notes\", \"type\": \"text\", \"label\": \"Notes\"}]',	NULL,	0,	0,	'',	1,	NOW(),	1,	NOW(),	'offline'),
('SKRILL',	'Skrill Account',	'[{\"code\": \"account_id\", \"type\": \"text\", \"label\": \"Account\", \"order\": null}, {\"code\": \"email\", \"type\": \"text\", \"label\": \"Email\", \"order\": null}, {\"code\": \"notes\", \"type\": \"text\", \"label\": \"Notes\", \"order\": null}]',	NULL,	1,	1,	'',	1,	NOW(),	1,	NOW(),	'offline');

UPDATE `setting` SET
`setting_value` = '{\"paymentOption\": \"BITCOIN\",\"configuration\": {\"autoDecline\": false, \"minutesInterval\": 20, \"maximumAllowedDeposit\": \"40\", \"minimumAllowedDeposit\": \"0.0001\"}, \"lockRatePeriodSetting\": {\"autoLock\": false, \"minutesLockDownInterval\": 20}, \"withdrawalConfiguration\": {\"maximumAllowedWithdrawal\": \"40\", \"minimumAllowedWithdrawal\": \"0.0001\"}}'
WHERE `setting_id` = '113';