payment.bitcoin_configuration_save:
    path: /setting/bitcoin/configuration/save
    defaults:
        _controller: PaymentBundle:Bitcoin:saveBitcoinSetting
    methods: [POST]

payment.bitcoin_rate_save:
    path: /rate/save
    defaults:
        _controller: PaymentBundle:Bitcoin:saveBitcoinRate
    methods: [POST]

payment.bitcoin_withdrawal_rate_save:
    path: /withdrawal-rate/save
    defaults:
        _controller: PaymentBundle:Bitcoin:saveBitcoinWithdrawalRate
    methods: [POST]

payment.bitcoin_confirmations_save:
    path: /payment/bitcoin/confirmations
    defaults:
        _controller: PaymentBundle:Bitcoin:saveBitcoinConfirmation
    methods: [POST]