services:
    media.manager:
        class: MediaBundle\Manager\MediaManager
        calls:
            - [ 'setContainer', ['@service_container'] ]
            - [ 'init' ]
    MediaBundle\Manager\MediaManager: '@media.manager'