services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TwoFactorBundle\Provider\:
        resource: '../../Provider/*'
        exclude: '../../Provider/Message/Exceptions'

    TwoFactorBundle\Provider\Message\Email\EmailMessenger:
        arguments:
            $template: '%2fa.email_template%'
    TwoFactorBundle\Provider\Message\Email\EmailProvider:
        tags:
            - { name: '2fa.provider', alias: 'email' }

    TwoFactorBundle\Provider\Message\Sms\SmsMessenger:
        arguments:
            $template: '%2fa.sms_template%'
    TwoFactorBundle\Provider\Message\Sms\SmsProvider:
        tags:
            - { name: '2fa.provider', alias: 'sms' }

    TwoFactorBundle\Validator\Constraints\:
        resource: '../../Validator/Constraints/*Validator.php'
        tags:
            - { name: validator.constraint_validator }