<?php

namespace DbBundle\Repository;

use Doctrine\ORM\AbstractQuery;

/**
 * CustomerGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerGroupRepository extends BaseRepository
{
    public function getListQb($filters)
    {
        $qb = $this->createQueryBuilder('cg');

        if (array_has($filters, 'search')) {
            $qb->andWhere('cg.name LIKE :search')->setParameter('search', '%' . $filters['search'] . '%');
        }

        $groupFilters = [];
        if (array_has($filters, 'filter')) {
            $groupFilters = array_get($filters, 'filter');

            if (!empty(array_get($groupFilters, 'from', ''))) {
                $qb->andWhere('cg.createdAt >= :from');
                $qb->setParameter('from', new \DateTime($groupFilters['from']));
            }

            if (!empty(array_get($groupFilters, 'to', ''))) {
                $qb->andWhere('cg.createdAt < :to');
                $qb->setParameter('to', (new \DateTime($groupFilters['to'] . '+1 day')));
            }
        }

        return $qb;
    }

    public function getList($filters = [], $orders = [], $selects = [], $hydrationMode = AbstractQuery::HYDRATE_OBJECT)
    {
        $aliases = $this->getAliases();
        $qb = $this->getListQb($filters);
        $qb->select($this->getPartials($qb, 'cg', $aliases, $selects));
        
        foreach ($orders as $order) {
            list($column, $dir) = explode(' ', trim(preg_replace('/\s+/', ' ', $order)));
            list($alias, $column) = explode('.', $column);
            $this->join($qb, $alias, $aliases);
            $qb->orderBy("$alias.$column", $dir);
        }

        if (isset($filters['length'])) {
            $qb->setMaxResults($filters['length']);
        }
        if (isset($filters['start'])) {
            $qb->setFirstResult($filters['start']);
        }
        $query = $qb->getQuery();
        $query->setFetchMode($this->getEntityName(), 'gateways', \Doctrine\ORM\Mapping\ClassMetadata::FETCH_LAZY);

        return $qb->getQuery()->getResult($hydrationMode);
    }

    public function setDefaultById($id, $default = false)
    {
        $qb = $this->createQueryBuilder('cg');

         $q = $qb->update('DbBundle:CustomerGroup', 'cg')
            ->set('cg.isDefault', ':default')
            ->where('cg.id != :id')
            ->setParameter('default', $default)
            ->setParameter('id', $id)
            ->getQuery();
        $q->execute();
    }

    public function getListFilterCount($filters = null)
    {
        $qb = $this->getListQb($filters);
        $qb->select('COUNT(cg.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getListAllCount()
    {
        $qb = $this->createQueryBuilder('cg');
        $qb->select('COUNT(cg.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getAvailableFilters()
    {
        return ['length', 'start', 'search', 'name', 'filter'];
    }

    public function getAliases($reverse = false)
    {
        if ($reverse) {
            return [
                '_main_' => 'cg',
            ];
        }

        return [
            'cg' => ['main' => true, 'i' => 'id', 'must' => ['name']],
        ];
    }

    public function getDefaultGroup($isDefault = 1, $hydrationMode = \Doctrine\ORM\Query::HYDRATE_OBJECT)
    {
        $qb = $this->createQueryBuilder('cg');
        $qb->where('cg.isDefault = :default')->setParameter('default', $isDefault);

        return $qb->getQuery()->getSingleResult($hydrationMode);
    }
}
