<?php

namespace DbBundle\Repository;

/**
 * CustomerGroupGatewayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerGroupGatewayRepository extends BaseRepository
{
    public function findByGroup($groups, $hydrationMode = \Doctrine\ORM\Query::HYDRATE_OBJECT)
    {
        $qb = $this->createQueryBuilder('cgg');
        $qb->leftJoin('cgg.gateway', 'g');
        $qb->select('g', 'cgg');
        $qb->andWhere('cgg.customerGroup IN (:groups)')->setParameter('groups', $groups);

        return $qb->getQuery()->getResult($hydrationMode);
    }
}
