<?php

namespace DbBundle\Repository;

/**
 * SmsCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
