template: MemberBundle:Member:index.html.twig
roles:
    - ROLE_CUSTOMER_VIEW
widgets:
    list:
        type: \AppBundle\Widget\Page\ListWidget
        properties:
            class: \DbBundle\Entity\Customer
            processResult: 'controller::processListResult'
            methods:
                records:
                    name: getCustomerList
                    params:
                        filters: []
                        orders: []
                        limit: 10
                        offset: 0
                totalFiltered:
                    name: getCustomerListFilterCount
                    params:
                        filters: []
                total:
                    name: getCustomerListAllCount
            additionalFilters:
                searchReferralName: 1
                searchWebsite: 1
                searchCampaign: 1
            recordUrl:
                route: customer.customer.update_page
                params:
                    id: ':id'
                    activeTab: profile
            columns:
                customer:
                    label: Username
                    type: text
                    from: customer.user.username
                product_username:
                    label: ProductId
                    type: function
                    function: getProductUsername
                    from: customer
                country:
                    label: Country
                    type: text
                    from: 'customer.country.name'
                # currency:
                #     label: Currency
                #     type: text
                #     from: customer.currency.code                                                    
                kyc:
                    label: KYC
                    type: function
                    function: listKyc
                    from: customer.verifiedAt
                date_joined:
                    label: Date Joined
                    type: date
                    from: customer.joinedAt
                    format: F j, Y
                created_by:
                    label: Created By
                    type: function
                    function: listCreator
                    from: customer.user.creator
                status:
                    label: Status
                    type: function
                    function: listStatus
                    from: customer
                action:
                    label: Action
                    type: function
                    function: listAction
                    attrs:
                        data-priority: 2
            filtersDom: <'form-inline'<'form-group m-r-10 ft-date'<'m-t-0 xs-date 'ft>>csgkopyar<'form-group' <'m-t-10'>>>
            search: :search
            filters:
                from:
                    label: From
                    type: date
                    dom: <'form-group form-group-sm m-r-10'<'input-group'i<^span 'input-group-addon bg-white text-default'<!'fa fa-calendar'!>>>>
                    symbol: f
                    attrs:
                        placeholder: From
                        type: input
                        class: form-control cls-date
                    applyOnChanged: 0
                    value: :from
                to:
                    label: To
                    type: date
                    dom: <'form-group form-group-sm m-r-10'<'input-group'i<^span 'input-group-addon bg-white text-default'<!'fa fa-calendar'!>>>>
                    symbol: t
                    attrs:
                        placeholder: To
                        type: input
                        class: form-control cls-date
                    applyOnChanged: 0
                    value: :to
                product:
                    label: Product
                    type: select
                    dom: <'form-group form-group-sm m-r-10 xs-filter'i>
                    symbol: p
                    class: selectpicker
                    applyOnChanged: false
                    attrs:
                        data-style: btn-white btn-sm
                        multiple: multiple
                        data-none-selected-text: Product
                        data-width: auto
                        data-size: 5
                    value: :product
                    choicesFrom:
                        function: '@product.manager::getProductList'
                        label: result['name']
                        value: result['id']
                paymentOption:
                    label: Payment Option
                    type: select
                    dom: <'form-group form-group-sm m-r-10 xs-filter'i>
                    symbol: o
                    class: selectpicker
                    applyOnChanged: false
                    attrs:
                        data-style: btn-white btn-sm
                        title: Payment Option
                        multiple: multiple
                        data-width: auto
                        data-size: 5
                    value: :paymentOption
                    choicesFrom:
                        function: '@paymentoption.manager::filter'
                        label: result.getName()
                        value: result.getCode()
                        from: data
                currencies:
                    dom: <'form-group form-group-sm m-r-10 xs-filter'i>
                    label: Currency
                    type: select
                    symbol: c
                    class: selectpicker
                    applyOnChanged: false
                    attrs:
                        data-style: btn-white btn-sm
                        title: Currency
                        multiple: multiple
                        data-width: auto
                        data-size: 5                                                 
                    value: :currency
                    choicesFrom:
                        function: '@currency.manager::getCurrencyList'
                        label: result['name'] ~ ' (' ~ result['code'] ~ ')'
                        value: result['id']
                country:
                    dom: <'form-group form-group-sm m-r-10 xs-filter'i>
                    label: Country
                    type: select
                    symbol: y
                    class: selectpicker
                    applyOnChanged: false
                    attrs:
                        data-style: btn-white btn-sm
                        title: Country
                        multiple: multiple
                        data-width: auto
                        data-size: 5
                    value: :country
                    choicesFrom:
                        function: '@country.manager::getCountryList'
                        label: result['name'] ~ ' (' ~ result['code'] ~ ')'
                        value: result['id']
                KYC:
                    dom: <'form-group form-group-sm m-r-10 xs-filter'i>
                    label: KYC
                    type: select
                    symbol: k
                    class: selectpicker
                    applyOnChanged: false
                    attrs:
                        data-style: btn-white btn-sm
                        title: KYC
                        multiple: multiple
                        data-width: auto
                        data-size: 5
                    value: :KYC
                    choices:
                        '1': Verified
                        '0': Not Verified
                status:
                    dom: <'form-group form-group-sm m-r-10 xs-filter'i>
                    label: Status
                    type: select
                    symbol: s
                    class: selectpicker
                    applyOnChanged: false
                    attrs:
                        data-style: btn-white btn-sm
                        title: Status
                        multiple: multiple
                        data-width: auto
                        data-size: 5
                    choices:
                        registered: Registered
                        enabled: Enabled
                        suspended: Suspended
                    value: :status
                tag:
                    dom: <'form-group form-group-sm m-r-10 xs-filter'i>
                    label: All Tags
                    type: select
                    symbol: g
                    class: selectpicker
                    applyOnChanged: false
                    attrs:
                        data-style: btn-white btn-sm
                        title: Tag
                        multiple: multiple
                        data-width: auto
                        data-size: 5
                    choices:
                        MBR: Member
                        AFF: Affiliate
                    value: :tag
                applyFilter:
                    attrs:
                        class: btn btn-sm btn-default
                resetFilter:
                    attrs:
                        class: btn btn-sm btn-inverse
