DbBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            groups: ['default']
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            groups: ['default']
    properties:
        username:
            - NotBlank:
                groups: ['default']
            - Regex:
                pattern: '/^[A-Za-z0-9\_\-]*$/u'
                match: true
                message: username.regex
                groups: ['default']
            - Length:
                min: 4
                max: 255
                minMessage: username.min
                maxMessage: username.max
                groups: ['default']
        password:
            - NotBlank:
                groups: ['withPassword']
            - Regex:
#                atleast 2 letter + 2 digit + 2 symbols
#                $notAllowed = [
#                    'A111111',
#                    'a111111',
#                    'AA111111',
#                    'aa111111',
#                    'aaaa#$',
#                    '$@aaaa#$',
#                    '1111#$',
#                    '$@1111#$'
#                ];
#
#                $allowed = [
#                    'aaaa11##',
#                    '@@11aaaa',
#                    '11$$aaaa',
#                    '11aaaa#$',
#                    '@#aaaa11',
#                    'aaaa%^11',
#                    'a2a2@@1s',
#                    'a2#a2@a2',
#                    '@2a@2s2$',
#                    '@a2@a4$a',
#                    '2@a4$a2$',
#                    'a2#a2#a2#',
#                    'a2222###a',
#                    '2xxxxx###2',
#                    '%2222aaa#'

#                ];
                pattern: /(?=^.{8,}$)(?=(.*[0-9]){2,})(?=(.*[A-Za-z]){2,})(?=(.*[+\-\/\{~\}!"^_`\[\]:$!@#%^&*\?]){2,})/
                match: true
                message: password.regex
                groups: ['withPassword', 'customer']
            - Length:
                min: 8
                minMessage: password.min
                groups: ['withPassword', 'customer']
        email:
            - NotBlank:
                groups: ['default']
            - Email:
                groups: ['default']
            - Length:
                max: 72
                groups: ['default']