services:
    widget.collection:
        class: AppBundle\Widget\CollectionWidget
        parent: app.widget_abstract
        calls:
            - [ 'setContainer', ['@service_container'] ]
            - [ 'setType', ['collection'] ]
        shared: false
        lazy: true
        tags:
            - { name: app.widget, widget_name: collection }
    widget.quotes:
        class: AppBundle\Widget\QuotesWidget
        parent: app.widget_abstract
        calls:
            - [ 'setType', ['quotes'] ]
        shared: false
        lazy: true
        tags:
            - { name: app.widget, widget_name: quotes }