imports:
    - { resource: handler.yml }
    - { resource: widgets.yml }

services:
    MemberBundle\Controller\SettingController:
        autoconfigure: true
        autowire: true
        public: false
        tags: ['controller.service_arguments']

    MemberBundle\Manager\MemberProductManager:
        autoconfigure: true
        autowire: true

    member.transformer.referrerTransformer:
        class: MemberBundle\Transformer\ReferrerTransformer
        lazy: true
        arguments:
            - '@doctrine'
            
    member.manager:
        class: MemberBundle\Manager\MemberManager
        autowire: true
        autoConfig: true
        parent: app.base_manager
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]
            - ['setTranslator', ['@translator']]
            - ['setEventDispatcher', ['@event_dispatcher']]
            - ['setSettingManager', ['@app.setting_manager']]
            - ['setCommissionManager', ['@commission.manager']]
            - ['setTransactionManager', ['@transaction.manager']]
            - ['setCurrencyManager', ['@currency.manager']]
            - ['setMemberProductRepository', ['@=service("doctrine").getRepository("DbBundle\\Entity\\CustomerProduct")']]
            - ['setMemberReferralNameRepository', ['@=service("doctrine").getRepository("DbBundle\\Entity\\MemberReferralName")']]
            - ['setMemberPaymentOptionRepository', ['@=service("doctrine").getRepository("DbBundle\\Entity\\CustomerPaymentOption")']]
            - ['setCurrencyRepository', ['@=service("doctrine").getRepository("DbBundle\\Entity\\Currency")']]
    MemberBundle\Manager\MemberManager: "@member.manager"
  
    member.inactive.manager:
        class: MemberBundle\Manager\InactiveMemberManager
        arguments: [ "@doctrine.orm.entity_manager", "@transaction.manager"]

    member.commission_manager:
        class: MemberBundle\Manager\MemberCommissionManager
        parent: app.base_manager

    member.revenue_share_manager:
        class: MemberBundle\Manager\MemberRevenueShareManager
        calls:
            - ['setMemberRevenueShareRepository', ['@=service("doctrine").getRepository("DbBundle\\Entity\\MemberRevenueShare")']]
        
    member.referral_name_manager:
        class: MemberBundle\Manager\MemberReferralNameManager
        parent: app.base_manager
        
    validator.member.max_active_referral_name_validator:
        class: MemberBundle\Constraints\MaxActiveReferralNameConstraintValidator
        arguments: [ "@doctrine", "@app.setting_manager" ]
        tags:
            - { name: validator.constraint_validator }

    member.website_manager:
        class: MemberBundle\Manager\MemberWebsiteManager
        parent: app.base_manager

    validator.member.unique_customer_product_constraint_validator:
        class: MemberBundle\Constraints\UniqueCustomerProductConstraintValidator
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: validator.constraint_validator, alias: alias }

    validator.member.max_active_website_validator:
        class: MemberBundle\Constraints\MaxActiveWebsiteConstraintValidator
        arguments: [ "@doctrine", "@app.setting_manager" ]
        tags:
            - { name: validator.constraint_validator }
