country.list_page:
    path:     /
    defaults: { _controller: CountryBundle:Default:index }
    
country.list_search:
    path:     /search
    defaults: { _controller: CountryBundle:Default:search }
    
country.view_page:
    path:     /view/{id}
    defaults: { _controller: CountryBundle:Default:view }
    
country.create_page:
    path:     /create
    defaults: { _controller: CountryBundle:Default:create }
    
country.update_page:
    path:     /update/{id}
    defaults: { _controller: CountryBundle:Default:update }
    
country.save:
    path:       /save/{id}
    defaults:   {_controller: CountryBundle:Default:save, id: new }
    condition:  "context.getMethod() in ['POST']"
