services:
    CountryBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        calls:
            - ['setContainer', ['@service_container']]

    country.manager:
        class: CountryBundle\Manager\CountryManager
        parent: app.base_manager
        
    # form type
    country.form_type.country:
        class: CountryBundle\Form\CountryType
        autowire: true
        autoconfigure: true
        tags:
            - { name: form.type }