services:
    country.manager:
        class: CountryBundle\Manager\CountryManager
        parent: app.base_manager
        
    # form type
    country.form_type.country:
        class: CountryBundle\Form\CountryType
        arguments: [ "@doctrine", "@router" ]
        tags:
            - { name: form.type }