DbBundle\Entity\Country:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: name
            groups: ['default']
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: code
            groups: ['default']
    properties:
        name:
            - NotBlank:
                groups: ['default']
            - Length:
                groups: ['default']
                min: 4
                max: 64
                minMessage: country.name.min
                maxMessage: country.name.max
            - Regex:
                groups: ['default']
                pattern: '/^[A-Za-z0-9\s\P{Han}]*$/u'
                match: true
                message: country.name.regex
        code:
            - NotBlank:
                groups: ['default']
            - Length:
                groups: ['default']
                min: 2
                max: 6
                minMessage: country.code.min
                maxMessage: country.code.max
            - Regex:
                groups: ['default']
                pattern: '/^[A-Za-z0-9\s\P{Han}]*$/u'
                match: true
                message: country.code.regex
        currency:
            - AppBundle\Validator\Constraints\Exists:
                entityClass: DbBundle\Entity\Currency
                valuePath: value.getId()
                column: id
                ignoreNull: true