version: '2.3'
services:
    bo:
        build:
            context: ../
            dockerfile: .docker/Dockerfile
            args:
                BASE_IMAGE: ${BASE_IMAGE}
                BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
        environment:
            SYMFONY_ENV: ${SYMFONY_ENV}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        depends_on:
            - database
    database:
        build:
            context: ./
            dockerfile: DockerfileMysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    googlechrome_remote:
        image: selenium/standalone-chrome:3.12.0-cobalt
        volumes:
            - /dev/shm:/dev/shm
