# root
root:
  path: /
  controller: App\Controller\DefaultController::index
 
# api piwi back office
api_piwi_back_office_test:
  path: /api/piwi-back-office/test
  controller: App\Controller\ApiPiwiBackOffice\ApiPiwiBackOfficeController::test
  requirements:
    _format: json
  defaults:
    _format: json

api_piwi_back_office_login:
  path: /api/piwi-back-office/login
  controller: App\Controller\ApiPiwiBackOffice\ApiPiwiBackOfficeController::login
  requirements:
    _format: json
  defaults:
    _format: json

# api pinnacle
api_pinnacle_test:
  path: /api/pinnacle/test
  controller: App\Controller\ApiPinnacle\ApiPinnacleController::test
  requirements:
    _format: json
  defaults:
    _format: json

api_pinnacle_login:
  path: /api/pinnacle/login
  controller: App\Controller\ApiPinnacle\ApiPinnacleController::login
  requirements:
    _format: json
  defaults:
    _format: json

api_pinnacle_deposit:
  path: /api/pinnacle/deposit
  controller: App\Controller\ApiPinnacle\ApiPinnacleController::deposit
  requirements:
    _format: json
  defaults:
    _format: json
  methods: [POST]

api_pinnacle_widthdraw:
  path: /api/pinnacle/widthdraw
  controller: App\Controller\ApiPinnacle\ApiPinnacleController::widthdraw
  requirements:
    _format: json
  defaults:
    _format: json
  methods: [POST]

api_pinnacle_users:
  path: /api/pinnacle/users
  controller: App\Controller\ApiPinnacle\ApiPinnacleController::users
  requirements:
    _format: json
  defaults:
    _format: json

# api piwi mwa
api_piwi_mwa_test:
  path: /api/piwi-back-office/test
  controller: App\Controller\ApiPiwiMWA\ApiPiwiMWAController::test
  requirements:
    _format: json
  defaults:
    _format: json

api_piwi_mwa_login:
  path: /api/piwi-back-office/login
  controller: App\Controller\ApiPiwiMWA\ApiPiwiMWAController::login
  requirements:
    _format: json
  defaults:
    _format: json

# blockchain apis
api_blockchain_exchange_rates:
  path: /api/blockchain/exchange-rates
  controller: App\Controller\ApiBlockChain\ApiBlockChainController::exchangeRates
  requirements:
    _format: json
  defaults:
    _format: json
  methods: [GET]

api_blockchain_generate_bitcoin_address:
  path: /api/blockchain/bitcoin-address
  controller: App\Controller\ApiBlockChain\ApiBlockChainController::generateBitcoinAddress
  requirements:
    _format: json
  defaults:
    _format: json
  methods: [POST]

api_blockchain_balance_update:
  path: /api/blockchain/balance-update
  controller: App\Controller\ApiBlockChain\ApiBlockChainController::balanceUpdate
  requirements:
    _format: json
  defaults:
    _format: json
  methods: [POST]

api_blockchain_to_bitcoin:
  path: /api/blockchain/currency-to-bitcoin
  controller: App\Controller\ApiBlockChain\ApiBlockChainController::convertToBitcoin
  requirements:
    _format: json
  defaults:
    _format: json
  methods: [POST]
