ApiBundle\Request\ChangePasswordRequest:
  group_sequence_provider: true
  getters:
    verificationCode:
      - TwoFactorBundle\Validator\Constraints\IsCodeCorrect:
          payloadPath: 'object.getVerificationPayload()'
          groups: [verification]
    currentPassword:
      - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
          message: "Incorrect current password"
          groups: [current]
    password:
      - NotBlank:
          groups: [new]
      - Regex:
          pattern: '/(?=^.{8,}$)(?=(.*[0-9]){2,})(?=(.*[A-Za-z]){2,})(?=(.*[+\-\/\{~\}!"^_`\[\]:$!@#%^&*\?]){2,})/'
          match: true
          message: "Password is invalid. Must be at least 8 characters, contain at least 2 letters, 2 digits and 2 symbols."
          groups: [new]
      - Expression:
          expression: "this.getPassword() !== this.getCUrrentPassword()"
          message: "New Password must not same to current password"
          groups: [new]
    repeatPassword:
      - Expression:
          expression: "this.getPassword() === this.getRepeatPassword()"
          message: "Password does not match"
          groups: [new]