commission.setting_page:
    path: /setting
    defaults:
        _controller: CommissionBundle:CommissionSetting:withWidget
        action: setting

commission.recompute_and_payout:
    path: /commission/{commissionPeriodId}/recompute-and-payout/
    defaults:
        _controller: CommissionBundle:CommissionSetting:recomputeAndPayout

commission.recompute_and_payout_revenue_share:
    path: /commission/{commissionPeriodId}/recompute-and-payout-revenue-share/
    defaults:
        _controller: CommissionBundle:CommissionSetting:recomputeAndPayoutRevenueShare