api_customers.me:
  path: me
  defaults:
    _controller: ApiBundle:Customer:me
  methods: [GET]

api_me_pinnacle_balance:
  path: me/pinnacle/balance
  defaults:
    _controller: ApiBundle:Member:getPinnacleBalance
  methods: [GET]

api_me_process_payment_options:
  path: me/processed-paymentoptions
  defaults:
    _controller: ApiBundle:PaymentOption:getMemberProcessPaymentOptions
  methods: [POST, GET]

api_me_active_paymentoptions:
  path: me/payment-options/active
  defaults:
    _controller: ApiBundle:Member:getActivePaymentOption
  methods: [GET]

api_me_transactions:
  path: me/transactions
  defaults:
    _controller: ApiBundle:TransactionOld:customerTransactions
  methods: [GET]

api_me_deposit:
  path: me/transactions/deposit
  defaults:
    _controller: ApiBundle:Transaction:deposit
  methods: [POST]

api_me_withdraw:
  path: me/transactions/withdraw
  defaults:
    _controller: ApiBundle:Transaction:withdraw
  methods: [POST]

api_me_transfer:
  path: me/transactions/transfer
  defaults:
    _controller: ApiBundle:Transaction:transfer
  methods: [POST]

api_me_last_bitcoin_transaction:
  path: me/transaction/last-bitcoin/{type}
  defaults:
    _controller: ApiBundle:Transaction:getLastBitcoinTransaction
  methods: [GET]

api_customers.me_acknowledge_bitcoin_transaction:
  path: me/transactions/acknowledge-bitcoin-transaction
  defaults:
    _controller: ApiBundle:Transaction:acknowledgeBitcoinTransaction
  methods: [POST]

api_member.change_password:
  path: me/change-password
  defaults:
    _controller: ApiBundle:Auth:changePassword
  methods: [POST]

api_member.change_locale:
  path: me/change-locale
  defaults:
    _controller: ApiBundle:Member:changeLocale
  methods: [POST]

api_member.change_country:
  path: me/change-country
  defaults:
    _controller: ApiBundle:Member:changeCountry
  methods: [POST]

api_customers.me_products:
  path: me/products
  defaults: { _controller: ApiBundle:Customer:customerProducts }
  methods: [GET]