api_members.register_member:
    path: register
    defaults:
        _controller: ApiBundle:Member:register
    methods: [POST]

api_customers.check_email_or_phone_number_if_exists:
    path: email-phone/check-if-exists
    defaults:
        _controller: ApiBundle:Customer:checkPhoneOrEmailIfExists
    methods: [POST]

api_customers.update_password:
    path: update-password
    defaults:
        _controller: ApiBundle:Customer:updatePassword
    methods: [POST]

api_customers.me_payment_options:
    path: payment-options
    defaults: { _controller: ApiBundle:Customer:customerPaymentOptions }
    methods: [GET]

api_customers.me_payment_option:
    path: payment-options/{id}
    defaults: { _controller: ApiBundle:Customer:customerPaymentOption }
    methods: [GET]

api_customers.me_notifications:
    path: notifications
    defaults: { _controller: ApiBundle:Customer:notifications }
    methods: [GET]

api_customers.me_read_notifications:
    path: read-notifications
    defaults: { _controller: ApiBundle:Customer:readNotifications }
    methods: [PUT]

api_customers.me_kyc_files:
    path: me/files
    defaults: { _controller: ApiBundle:Member:getMemberFiles }
    methods: [GET]

api_customers.me_kyc_upload:
    path: me/files
    defaults:
        _controller: ApiBundle:Member:uploadMemberFile
    methods: [POST]

api_customers.me_kyc_render:
    path: me/file/{filename}
    defaults:
        _controller: ApiBundle:Member:renderMemberFile

api_customers.me_kyc_file_uri:
    path: me/file/uri/{filename}
    defaults:
        _controller: ApiBundle:Member:getMemberFileUri

api_customers.me_kyc_delete:
    path: me/file/{filename}/delete
    defaults:
        _controller: ApiBundle:Member:deleteMemberFile
    methods: [POST]

api_member.me_requests:
    path: me/requests
    defaults:
        _controller: ApiBundle:MemberRequest:memberRequests
    methods: [GET]