api_paymentoptions.get_cached_bitcoin_adjustment:
    path: paymentoptions/bitcoin-adjustment/{type}
    defaults:
        _controller: ApiBundle:PaymentOption:getCachedBitcoinAdjustment
    methods: [GET]