api_promo.details:
    path: promo/{code}
    defaults:
        _controller: ApiBundle:Promo:search
    methods: [GET]

api_promo.members:
    path: promo/{code}/members
    defaults:
        _controller: ApiBundle:Promo:members