services:
    TwoFactorBundle\Provider\Message\Sms\TwilioSmsMessenger:
        arguments:
            - '@monolog.logger.twilio'
            - '%twilio_sid%'
            - '%twilio_token%'
            - '%twilio_from%'

two_factor:
    messenger:
        template_provider: 'TwoFactorBundle\Provider\Message\TemplateProvider\TemplateProvider'
        sms:
            sms_messenger_service: 'TwoFactorBundle\Provider\Message\Sms\TwilioSmsMessenger'
            templates:
                default: 'default.plain'
                register: 'account_activation.plain'
        email:
            templates:
                default: 'default.html'
                register: 'account_activation.html'
    storage: 'DbBundle\Repository\TwoFactorCodeRepository'
