# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        DbBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        doctrine:
            entity:
                class: DbBundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            security:   false

        api_doc:
            pattern:  ^/(%app_locales%)/api/doc
            security: false

        api_login:
            pattern: ^/(%app_locales%)/api/auth/(login|logout|refreshtoken)
            security: false

        
        api_registration:
            pattern: ^/(%app_locales%)/api/member/register
            security: false    

        api_2fa:
            pattern: ^/(%app_locales%)/api/2fa/requestcode
            security: false        

        api_check_account:
            pattern: ^/(%app_locales%)/api/member/email-phone/check-if-exists
            security: false    

        api:
            pattern:    ^/(%app_locales%)/api
            anonymous: false
            fos_oauth:  true
            stateless:  true

        payment:
            pattern: ^/payment
            security: false
        
        blockchain:
            pattern: ^/blockchain
            security: false

        main:
            pattern: ^/
            anonymous: ~
            security: true
            provider: doctrine
            logout:
                path: app.logout
                target: app.login_page
                success_handler: app.logout_handler
            form_login:
                login_path: app.login_page
                check_path: app.login_check
                default_target_path: app.dashboard_page

    access_control:
        - { path: ^/(%app_locales%)/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        -
            path: ^/(%app_locales%)/api/me
            allow_if: "has_role('ROLE_MEMBER')"

        - { path: ^/(%app_locales%)/api, roles: [ROLE_API] }
        - { path: ^/(%app_locales%)/api/customers, roles: [ROLE_API] }
        - { path: ^/, roles: [ROLE_ADMIN,ROLE_MAINTENANCE] }
