DbBundle\Entity\PaymentOption:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: code
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: name
    properties:
        code:
            - NotBlank: ~
            - Regex:
                pattern: '/^[A-Za-z0-9\s\P{Han}]*$/u'
                match: true
                message: title.regex
            - Length:
                min: 2
                max: 16
                minMessage: title.min
                maxMessage: title.max
        name:
            - NotBlank: ~
            - Length:
                min: 2
                max: 64
                minMessage: title.min
                maxMessage: title.max